### ISSUE TITLE
Optional automatic handling of anti-flood limitations

### ISSUE THREAD

**Issue by thehowl** [go-telegram-bot-api/telegram-bot-api#101]
The `ResponseParameters` provides a `retry_after` field that specifies the number of seconds to wait before making the same request. I suggest to add a **disabled by default** setting to make this done by the library - if a request has been refused due to flood limitations, do it again after the specified number of seconds.

**Comment by zhulik** [comment]
Ok, imagine you have a bot with thousands users. Someday you will reach the telegram flood limit and library will do nothing except resending messages, that means resource leaking(resend queue will grow) and bot DOS for all users. 

Sometimes it's better to ignore repeating. As bot developer you can handle flood limit responses by youself and decide to repeat the request or not. 

I think telegram-bot-api is a bad place to put message resending code.

**Comment by Syfaro** [comment]
Given that with the current state of the library it's impossible to get the `ResponseParameters` without manually creating the requests yourself, it might not be a terrible idea. Alternatively, somehow exposing that and allow users to manually work with it with their own retry logic.

**Comment by Syfaro** [comment]
Closing as #153 allows access to the `ResponseParameters`.
