### ISSUE TITLE
Mention user by User ID

### ISSUE THREAD

**Issue by Anakros** [go-telegram-bot-api/telegram-bot-api#110]
Is it even possible? I saw markdown syntax for it in [MadelineProto](https://github.com/danog/MadelineProto) docs: `[Daniil Gentili](mention:123456789)`, but it doesn't work for me (my client just displays text instead of a link to user).

**Comment by Syfaro** [comment]
I can't find that in the [documentation](https://core.telegram.org/bots/api#markdown-style), nor can I find any mentions of that syntax elsewhere, so I would assume it is not possible.

**Comment by Anakros** [comment]
Thanks anyway.
