### ISSUE TITLE
Consider to use this library

### ISSUE THREAD

**Issue by olebedev** [go-telegram-bot-api/telegram-bot-api#112]
Hi guys, 

just to let you know. There is [yet another library](https://github.com/olebedev/go-tgbot) for telegram bot API but with the completely different approach - this lib is almost all generated from the swagger description. So, it's quite simple to keep the lib up-to-date with the API and no need to learn yet another library. Please, take a look at [benefits](https://github.com/olebedev/go-tgbot#usage-benefits) and try to your next project. 

Happy coding, thanks!

**Comment by Syfaro** [comment]
This is not the place for unsolicited advertisements for your library.
