### ISSUE TITLE
How to use payments

### ISSUE THREAD

**Issue by qoops-1** [go-telegram-bot-api/telegram-bot-api#116]
Couldn't quite figure out how to make payments with your library. I found the `AnswerPreCheckoutQuery` and `AnswerShippingQuery` methods, however, how do I `sendInvoice`? There's `Pay` field in `InlineKeyboard` button, but I don't think it does anything. Where do I enter my payment provider token and other info?

**Comment by DaBlitzStein** [comment]
+1

**Comment by zhuharev** [comment]
@qoops-1, @DaBlitzStein you can do it on `BotFather` bot
![2017-10-05-170002_328x153_scrot](https://user-images.githubusercontent.com/10848952/31231160-b292f49e-a9ee-11e7-8613-94a778145c5c.png)
![2017-10-05-170016_441x397_scrot](https://user-images.githubusercontent.com/10848952/31231159-b287fef4-a9ee-11e7-80e8-257171156e86.png)

**Comment by zhuharev** [comment]
@qoops-1 have you dealt with your problem?

**Comment by qoops-1** [comment]
@zhuharev nope, choosing payment provider is irrelevant here. I was talking about sending an invoice. Do you have any working code that creates the invoice? Because I think there's a function missing in the framework, with a different framework everything has worked fine

**Comment by Syfaro** [comment]
`InvoiceConfig` (which can be created with the helper function `NewInvoice`) is `Chattable`, so you can send it using the same `Send` function as you'd use for any message.

**Comment by zhuharev** [comment]
@qoops-1, @Syfaro right 

you can just send `InvoiceConfig`
https://github.com/go-telegram-bot-api/telegram-bot-api/blob/6b5102fab5586322d6fe98112fc671ad23dfae33/configs.go#L934-L952

below is a fully working example:

```go
package main

import (
	"log"
	"os"
	"strconv"

	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api"
)

func main() {

	var (
		token        = os.Getenv("TBOTAPI_TOKEN")
		paymentToken = os.Getenv("TBOTAPI_PAYMENT_TOKEN")
		testerID, _  = strconv.ParseInt(os.Getenv("TBOTAPI_TESTER_ID"), 10, 64)
	)

	bot, err := tgbotapi.NewBotAPI(token)
	checkErr(err)

	u := tgbotapi.NewUpdate(0)
	u.Timeout = 60

	updates, err := bot.GetUpdatesChan(u)
	checkErr(err)

	// create invoice
	invoice := tgbotapi.NewInvoice(testerID, "Test invoice", "description here", "custom_payload",
		paymentToken, "start_param", "USD",
		&[]tgbotapi.LabeledPrice{{Label: "USD", Amount: 200}})
	_, err = bot.Send(invoice)
	checkErr(err)

	// optional offer delivery options ShippingQuery

	for update := range updates {
		if update.PreCheckoutQuery != nil {
			handlePreCheckoutQuery(bot, update)
			return
		}

		// optional handle ShippingQuery
	}
}

func handlePreCheckoutQuery(bot *tgbotapi.BotAPI, update tgbotapi.Update) {
	pca := tgbotapi.PreCheckoutConfig{
		OK:                 true,
		PreCheckoutQueryID: update.PreCheckoutQuery.ID,
	}
	_, err := bot.AnswerPreCheckoutQuery(pca)
	checkErr(err)
}

func checkErr(err error) {
	if err != nil {
		log.Fatalln(err)
	}
}

```

**Comment by devig** [comment]
How I can send Invoice in channel using @channelname ?
`NewInvoice(chatID **int64**`

**Comment by tingwei628** [comment]
I can't find this method`AnswerPreCheckoutQuery` in `tgbotapi.BotAPI` (v5.5.1)

**Comment by tingwei628** [comment]
In v5, use `bot.Request(pca)` instead of `bot.AnswerPreCheckoutQuery(pca)` ()

**Comment by tingwei628** [comment]
In v5, use `bot.Request(pca)` instead of `bot.AnswerPreCheckoutQuery(pca)`

**Comment by cruzluna** [comment]
`cannot use &[]tgbotapi.LabeledPrice{…} (value of type *[]tgbotapi.LabeledPrice) as type []tgbotapi.LabeledPrice in argument to tgbotapi.NewInvoice`
