### ISSUE TITLE
Bot crashes sometimes when tries to get command

### ISSUE THREAD

**Issue by dfomin** [go-telegram-bot-api/telegram-bot-api#117]
Bot crashes sometimes with this output:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x58 pc=0x5117e8]

goroutine 1 [running]:
panic(0x7ad240, 0xc82000a0f0)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
gopkg.in/telegram-bot-api%2ev4.(*Message).Command(0x0, 0x0, 0x0)
        /home/dfomin/projects/go/src/gopkg.in/telegram-bot-api.v4/types.go:161 +0x28
main.main()
        /home/dfomin/projects/test/server.go:122 +0x5e8
```

This is the line 122 from server.go:
`command := update.Message.Command()`

I'm using last stable version gopkg.in/telegram-bot-api.v4

**Comment by zhulik** [comment]
Message can be nil. It is ok when user sends photo, video, document or sticker

**Comment by dfomin** [comment]
What is the best place to check it?
```
if m == nil || !m.IsCommand() {
```
in `func (m *Message) Command() string`
or check it in custom code?

**Comment by zhulik** [comment]
There is no message for calling Command(). It is nil. Make a nil check in your code

**Comment by dfomin** [comment]
Thank you for support.
