### ISSUE TITLE
Get File

### ISSUE THREAD

**Issue by rachmanzz** [go-telegram-bot-api/telegram-bot-api#119]
I'm new in go..
How to get file like image, document, audio if user sending that file?

**Comment by Syfaro** [comment]
After you get the FileID from the Message, you can get a direct link to the file with [this method](https://github.com/go-telegram-bot-api/telegram-bot-api/blob/master/bot.go#L207-L210).

**Comment by DeathStarName** [comment]
> After you get the FileID from the Message, you can get a direct link to the file with [this method](https://github.com/go-telegram-bot-api/telegram-bot-api/blob/master/bot.go#L207-L210).

How i can get FileID from message ? Give me example please
