### ISSUE TITLE
chat.IsGroup() = true in private chat between User and bot

### ISSUE THREAD

**Issue by chaKlug** [go-telegram-bot-api/telegram-bot-api#120]
Hello. Have some situation.
```
chat := tgbotapi.Chat{ID: chatID, Type: "group"}
ok = chat.IsGroup()
```
, where chatID - conversation id between user and bot

How it can be true, if group chat is chat where participants are more than two?

**Comment by zhuharev** [comment]
@chaKlug why set manually `"group"`?

check following lines:
https://github.com/go-telegram-bot-api/telegram-bot-api/blob/master/types.go#L109-L112
