### ISSUE TITLE
Support API 3.2 and 3.3

### ISSUE THREAD

**Issue by toby3d** [go-telegram-bot-api/telegram-bot-api#121]
## 3.3
- [ ] `Bots can now mention users via inline mentions, without using usernames.`
- [ ] `getChat now also returns pinned messages in supergroups, if present. Added the new field pinned_message to the Chat object.`
- [ ] `Added the new fields author_signature and forward_signature to the Message object.`
- [ ] `Added the new field is_bot to the User object.`

## 3.2
- [ ] `Added new methods for working with stickers: getStickerSet, uploadStickerFile, createNewStickerSet, addStickerToSet, setStickerPositionInSet, and deleteStickerFromSet.`
- [ ] `Added the fields set_name and mask_position to the Sticker object, plus two new objects, StickerSet, and MaskPosition.`

**Comment by simt2** [comment]
I have implemented API 3.2 in my [fork](https://github.com/simt2/telegram-bot-api/tree/api-3.2). There are still issues concerning the tests and I will send a pull request when I'm done testing with my own bots. Comments welcome, I'm not sure if I have followed the general structure concerning configs etc. correctly.
