### ISSUE TITLE
Additional project maintainers

### ISSUE THREAD

**Issue by Syfaro** [go-telegram-bot-api/telegram-bot-api#122]
Hi all, 

I don't really have enough time to be putting into this project lately. If anyone would like to help maintain it, please let me know, preferably via [Telegram](https://telegram.me/Syfaro).

**Comment by 733amir** [comment]
I will be glad to help maintain it.
I contacted you via Telegram but it seems:

1. It's been a long time since you checked your Telegram
2. There were a lot of messages and mine was buried under them.
