### ISSUE TITLE
incomplete error messages

### ISSUE THREAD

**Issue by aliforever** [go-telegram-bot-api/telegram-bot-api#128]
Hi.
When there's an error while sending a request, it doesn't output full error message.
For example, when user has blocked the bot, I receive forbidden in error rather than BOT_WAS_BLOCKED_BY_USER
Or sometimes I receive Bad Request errors and I can't say why there's a bad request because it doesn't mention details.
```
edit := tgbotapi.NewEditMessageText(int64(chatId), messageId, text)
message, err := bot.Api.Send(edit)
if err != nil {
     fmt.Println(message, err) // Here it returns an empty message and Bad Request
}
```

**Comment by aliforever** [comment]
I was talking to some nice people on Telegram and apparently the api doesn't return full error messages when status codes are not OK.
Would this get fixed in the future? Thanks

**Comment by zhuharev** [comment]
@aliforever fix it in master

use `go get -u github.com/go-telegram-bot-api/telegram-bot-api`
