### ISSUE TITLE
Helper function to send files to channel

### ISSUE THREAD

**Issue by aryahadii** [go-telegram-bot-api/telegram-bot-api#135]
I don't know if any helper function exists to send photos, videos or any other files to public channel

**Comment by zhuharev** [comment]
for upload file to public
```go
msg := tgbotapi.PhotoConfig{
		tgbotapi.BaseFile: BaseFile{
			BaseChat:    tgbotapi.BaseChat{ChannelUsername: "@channelname"},
			File:        "image.jpg",
		},
	}
bot.Send(msg)
```

now tgbotapi have only [NewPhotoUpload](https://godoc.org/github.com/go-telegram-bot-api/telegram-bot-api#NewPhotoUpload) helper
