### ISSUE TITLE
Telegram and method Send Photo

### ISSUE THREAD

**Issue by marinaAj** [go-telegram-bot-api/telegram-bot-api#137]
Hi
I try to use method sendPhoto from my PC to Telegram bot

https://api.telegram.org/bot12345678/sendPhoto?chat_id=<chat_id>&photo=file:///D:/TestImageJPG.jpg

But It doesn't work

If I use
https://api.telegram.org/bot12345678/sendMessage?chat_id=<chat_id> &text=  URL photo (https://i.mycdn.me/i?r=ADGc-AHOhhk0xU4_G5aVlnAECGRm3fig_cX1pJkGgx7jKyFEKHwKiL9QuGcq4J-B13c) 

it is work

How can I solution this problem?

**Comment by bjrne** [comment]
Hey marinaAj, are you using this library? This library is for the programming language go(lang), your example seems to be pure HTTP-Requests, so this would normally be the wrong place to search for help.
The problem you described seems to be that the bottom link to the picture is reachable through the internet, so the telegram api can find it. This link on the top is a link that only works on your computer, so when you send the request to the api on the internet, it doesn't know where to find it. 

This library takes care of that, so I'd advise you to use a library in a programming language of your choice, there are many out there. It just makes things a lot easier. If you're using this library already, please provide the relevant go code so we can resolve the problem. I hope this helps :)

**Comment by bjrne** [comment]
Hey marinaAJ, im going to close this for now, feel free to reopen it if you continue to have problems with this library and not the telegram API itself.
