### ISSUE TITLE
Can't understand NewPhotoUpload()

### ISSUE THREAD

**Issue by xuxubla** [go-telegram-bot-api/telegram-bot-api#138]
I read a lot of issues here about upload new photos but still did not understand and did not find the solution. There is my code:
```
file, err := url.Parse("https://cdn.f1ne.ws/images/6c6cb52-3c73f9d.png")
if (err == nil) {
	msg := tgbotapi.NewPhotoUpload(update.Message.Chat.ID, file)
	PrettyPrint(msg) // print object
	bot.Send(msg)
}
```
Here is my message:
```
{
   "ChatID": 102096060,
   "ChannelUsername": "",
   "ReplyToMessageID": 0,
   "ReplyMarkup": null,
   "DisableNotification": false,
   "File": {
     "Scheme": "https",
     "Opaque": "",
     "User": null,
     "Host": "cdn.f1ne.ws",
     "Path": "/images/6c6cb52-3c73f9d.png",
     "RawPath": "",
     "ForceQuery": false,
     "RawQuery": "",
     "Fragment": ""
   },
   "FileID": "",
   "UseExisting": false,
   "MimeType": "",
   "FileSize": 0,
   "Caption": ""
}
```
If I use path to static file everything is ok:
`msg := tgbotapi.NewPhotoUpload(update.Message.Chat.ID, "./file.png")`
So does anyone know how to upload new photo by URL?

P.S This solution didn't help:
```
msg := tgbotapi.NewPhotoUpload(update.Message.Chat.ID, nil)
msg.FileID = "http://.../..png"
msg.UseExisting = true
```

**Comment by zhuharev** [comment]
try just send string `msg := tgbotapi.NewPhotoUpload(update.Message.Chat.ID, "https://cdn.f1ne.ws/images/6c6cb52-3c73f9d.png")`

**Comment by xuxubla** [comment]
No errors but response is empty.

**Comment by xuxubla** [comment]
Nobody knows?
By the way Happy New Year!

**Comment by BartWillems** [comment]
This is what I use to send images:

`
res, err := http.Get(url)

if err != nil {
	// error handling...
}

content, err := ioutil.ReadAll(res.Body)

if err != nil {
	// error handling...
}

bytes := tgbotapi.FileBytes{Name: "image.jpg", Bytes: content}
msg := tgbotapi.NewPhotoUpload(message.Chat.ID, bytes)

msg.Caption = message.CommandArguments()
msg.ReplyToMessageID = message.MessageID
_, e := bot.Send(msg)
`

**Comment by GhostRussia** [comment]
At me works here so:
```
msg := tgbotapi.NewPhotoShare(message.Chat.ID, "http://.../image.jpg")
bot.Send(msg)
```

**Comment by Syfaro** [comment]
As was pointed out, you can pass your URL as a string to `NewPhotoShare`.
