### ISSUE TITLE
The development discussion group link in telegram is invalid

### ISSUE THREAD

**Issue by dariubs** [go-telegram-bot-api/telegram-bot-api#139]

**Comment by Syfaro** [comment]
I’m not sure why this keeps happening, it was previously reported (#69), but it seems to work fine for me and there are people continuing to join. 

Can you search for go_telegram_bot_api in Telegram directly?

**Comment by dc0d** [comment]
Link is still invalid and `go_telegram_bot_api` can not be found.

**Comment by Syfaro** [comment]
If someone who can't get it to work could try searching for it in the [web Telegram client](https://web.telegram.org), that'd be helpful. If you still can't find it in search, send the link to yourself and open the link using the web client, it should give you a more detailed error message.

**Comment by dc0d** [comment]
Web Client test:

### Not found
There is no Telegram account with the username you provided.

```
Method: contacts.resolveUsername
Result: {"_":"rpc_error","error_code":400,"error_message":"USERNAME_NOT_OCCUPIED"}
```

(https://pasteboard.co/H0sP1tL.png)

**Comment by Syfaro** [comment]
Apparently, public supergroups don't work in Iran currently. Not sure if anyone is attempting to join from there. 

Could you try using this invite link? https://t.me/joinchat/Ai1mXj56oudB--j5F56HVA

**Comment by dc0d** [comment]
Sad. Thanks for the followup!

Web response:

---

### Access denied
You are not allowed for this action.

```
Method: channels.getFullChannel
Result: {"_":"rpc_error","error_code":403,"error_message":"CHANNEL_PUBLIC_GROUP_NA"}
```

---
