### ISSUE TITLE
Question: Provide documentation for tgbotapi.UploadFile

### ISSUE THREAD

**Issue by issmirnov** [go-telegram-bot-api/telegram-bot-api#148]
Hello all,

I'd love to get some help understanding the usage of [UploadFile](https://github.com/go-telegram-bot-api/telegram-bot-api/blob/master/bot.go#L127). The current documentation states:
```
// Requires the parameter to hold the file not be in the params.
// File should be a string to a file path, a FileBytes struct,
// a FileReader struct, or a url.URL.
func (bot *BotAPI) UploadFile(endpoint string, params map[string]string, fieldname string, file interface{}) (APIResponse, error) {
```

I can't compute this doc statement. There's multiple arguments to this function, and it's extremely unclear what they mean. We have `endpoint`, `params`, `fieldname`, and `file`. The only one that I'm clear on is `file`.

My goal: send a simple text file: `./mybot -file ./hello_world`. 

Can someone provide a sample way to construct a message that sends a file? I see that @zhulik sent a refactor touching this code a while back.

Thanks!

**Comment by Syfaro** [comment]
You shouldn’t need to use this method. 

Look at the helpers for new document, photo, etc. and send those using the Send method.

**Comment by issmirnov** [comment]
Ah, Documents refers to files as well. Got it, thank you. For future visitors, here is the code that worked for me:

```
package main

import (
	"log"

	"gopkg.in/telegram-bot-api.v4"
)

const (
	username = "myusername"
	chatID   = 12356 // get this from debug logs
)

func main() {
	bot, err := tgbotapi.NewBotAPI("YOUR_TOKEN_HERE")
	if err != nil {
		log.Panic(err)
	}

	bot.Debug = true

	msg := tgbotapi.NewDocumentUpload(chatID, "my_file.txt")
	bot.Send(msg)
}
```

**Comment by vgxbj** [comment]
Thank you, this saved my day!

**Comment by sifaaa** [comment]
max 20 mb ?

**Comment by durant2021** [comment]
thank you @issmirnov it's work!
