### ISSUE TITLE
SendVideo doesn't work for iPhone

### ISSUE THREAD

**Issue by pyed** [go-telegram-bot-api/telegram-bot-api#15]
the testing has been done with the following code.

```Go
package main

import (
	"log"

	"github.com/Syfaro/telegram-bot-api"
)

func main() {
	bot, err := tgbotapi.NewBotAPI("YourAwesomeAPIToken")
	if err != nil {
		log.Panic(err)
	}

	bot.Debug = true

	log.Printf("Authorized on account %s", bot.Self.UserName)

	u := tgbotapi.NewUpdate(0)
	u.Timeout = 60

	err = bot.UpdatesChan(u)
	if err != nil {
		log.Panic(err)
	}

	videofile := "1.mp4"
	for update := range bot.Updates {
		log.Printf("[%s] %s", update.Message.From.UserName, update.Message.Text)

		msg := tgbotapi.NewMessage(update.Message.Chat.ID, "video on the way")
		msg.ReplyToMessageID = update.Message.MessageID

		bot.SendMessage(msg)

		newVid := tgbotapi.NewVideoUpload(update.Message.Chat.ID, videofile)
		if _, err := bot.SendVideo(newVid); err != nil {
			log.Panic(err)
		}
	}
}
```
I tested sending videos with multiple `mp4` files and they all show the same behavior, when the bot sends them they will have no thumbnail, and the time of the video will be `00:00`, also I should mention that on the iPhone Telegram app they can not be played!, it will just show a black background, on the OS X client it will work, but as I said, no thumbnail and no time.

I don't think that this is an API issue, because the OS X client handles them perfectly, using the drop-in feature it will ask you to send them with compression or "in a quick way", if you choose without compression I believe it will send them as a document, with the compression they'll be okay.

for testing you could download this `http://i.imgur.com/CGaKrhh.gifv`

**Comment by Syfaro** [comment]
My best guess is that Telegram for Mac is reencoding them in a different format, I'll have to play around with that.

**Comment by Syfaro** [comment]
I'm closing this issue because it's obviously related to encoding issues, not some issue with this library.
