### ISSUE TITLE
Removing InlineKeyboard on sending EditMessageTextConfig

### ISSUE THREAD

**Issue by GooG2e** [go-telegram-bot-api/telegram-bot-api#158]
Hello!
I have tried to edit message with inline keyboard using NewEditMessageText
When I send created object InlineKeyboard was deleted
Problem was removed only when I have generated InlineKeyboard again and pass it to BaseEdit object
I think this is an error
Thank you

**Comment by Syfaro** [comment]
It looks like editing a message without sending a new keyboard would remove the keyboard. 

I can't see anything in the code that would suggest this is in an error in the library (perhaps try turning on debug and making sure it's not passing something for `reply_markup`?) and the [documentation](https://core.telegram.org/bots/api#editmessagetext) doesn't suggest they're saved between message updates.
