### ISSUE TITLE
ForwardFromMessageID == 0

### ISSUE THREAD

**Issue by leonnash23** [go-telegram-bot-api/telegram-bot-api#161]
I try to set ReplyToMessageID == ForwardFromMessageID, but ForwardFromMessageID  always return 0

**Comment by zhuharev** [comment]
you can reply only for message (message can contain forwarded message). used messageID instead

**Comment by leonnash23** [comment]
@zhuharev forward message has field forward_from_message_id:
`forward_from_message_id | Integer | Optional. For messages forwarded from channels, identifier of the original message in the channel.`
So it works only for channels or it should work for a chat with bot too?
