### ISSUE TITLE
Blocked Telegram in Russia

### ISSUE THREAD

**Issue by NovikovRoman** [go-telegram-bot-api/telegram-bot-api#163]
As you know, telegrams were blocked in Russia and this caused difficulties in working with the bot. Can I add a proxy to the core when I request it?

**Comment by ilyaglow** [comment]
To use simple http proxy just set `HTTP_PROXY` environment variable. Socks5 can be handled with a proxified dialer and custom `*http.Client` which you should pass to `NewBotAPIWithClient(token string, client *http.Client)` function instead of `NewBotAPI(token string)`.

**Comment by Kataklysm** [comment]
#164

**Comment by Syfaro** [comment]
You can just pass a custom `http.Client` when initializing it as was previously mentioned.

**Comment by zhang12c** [comment]
Thank you
@ilyaglow
