### ISSUE TITLE
Different types of ID

### ISSUE THREAD

**Issue by ShoshinNikita** [go-telegram-bot-api/telegram-bot-api#167]
I found out that User.ID has type int, but Chat.ID – int64. I thought they are same, but this fact made me be confused. Can anyone explain this situation?

**Comment by Syfaro** [comment]
Supergroups have Chat IDs bigger than an int32 could store. 

From Telegram's docs on chats: 

> Unique identifier for this chat. This number may be greater than 32 bits and some programming languages may have difficulty/silent defects in interpreting it. But it is smaller than 52 bits, so a signed 64 bit integer or double-precision float type are safe for storing this identifier.

**Comment by ShoshinNikita** [comment]
Maybe, it would be better to use int64 everywhere?

**Comment by nathan0** [comment]
I've found a slight issue with this where `int64` would be best used everwhere, if I try to send a `tgbotapi.NewAnimationShare` it requires an `int64`, but `update.Message.ReplyToMessage.ForwardFrom.ID` is only `int32`, so I'm having to do `var sendTo = int64(update.Message.ReplyToMessage.ForwardFrom.ID)`
