### ISSUE TITLE
markdown parse error

### ISSUE THREAD

**Issue by Sherlock-Holo** [go-telegram-bot-api/telegram-bot-api#174]
when a text just have one `_` and I don't want to make it italic, it will cause an error `Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 148` , this byte is `95` and convert it to char it is `_`

**Comment by Syfaro** [comment]
This library doesn’t touch your text, it’s Telegram having issues with it. 

It might be possible to escape it with a `\` but I’m not sure.

**Comment by XSAM** [comment]
Thanks, @Syfaro. I escape the `_` with `\`, and it works fine.
