### ISSUE TITLE
how to set allowed_updates ?

### ISSUE THREAD

**Issue by patachi** [go-telegram-bot-api/telegram-bot-api#181]
missing allowed_updates in [WebhookConfig](https://github.com/go-telegram-bot-api/telegram-bot-api/blob/4c16a90966d12d963e19e4df99e7744c191d0e79/configs.go#L846) or is there some kind of workaround for this ?

https://core.telegram.org/bots/api#setwebhook

**Comment by Syfaro** [comment]
Resolved in https://github.com/go-telegram-bot-api/telegram-bot-api/commit/4d758f17d47eba8951d7810190e907db56e51801#diff-1de7f560481199d45fd6fea3a55890f8R739
