### ISSUE TITLE
Update example deploy bot with google app engine.

### ISSUE THREAD

**Issue by halink0803** [go-telegram-bot-api/telegram-bot-api#187]
Currently there is an example to run bot with Google App Engine, however, that example using NewBotAPI function which do not pass appengine urlfetch http client, that make the bot cannot be initiate. Can you guys update the docs so the newcomer like me can easier to run the bot.

Thank you,

**Comment by Syfaro** [comment]
It is possible to pass a `http.Client` in the [`NewBotAPIWithClient`](https://github.com/go-telegram-bot-api/telegram-bot-api/blob/master/bot.go#L43) method.
