### ISSUE TITLE
how to add user to group

### ISSUE THREAD

**Issue by pytimer** [go-telegram-bot-api/telegram-bot-api#188]
Hi, I am beginner. I want to know how to add a user to the specfied group? 

I search on the internet, many people say bots can not add user to group, is it right?

Thanks anyone for help.

**Comment by x1nfly** [comment]
If a bot can add users to group, don't you think it's unreasonable? Who wants to be pulled into an unknown group without knowing.

So the official bot API won't support it. You can use the Telegram API to create a thirdparty client, it has permissions to do you want.

**Comment by pytimer** [comment]
Thanks for your reply.
I find a Telegram API client in python, but i didn't find the client with go. Do you know which Telegram client with go? Or what docs can be referenced to implement this client.

**Comment by pytimer** [comment]
Thanks. I will try to create a client. :-)

**Comment by bjrne** [comment]
Since this is not specific to this framework I'll close the issue, I hope you found a solution to your problem.
