### ISSUE TITLE
EOF Calling AnswerInlineQuery

### ISSUE THREAD

**Issue by dc0d** [go-telegram-bot-api/telegram-bot-api#190]
I am getting lots of `EOF` errors when calling `AnswerInlineQuery`. Is there any settings to improve this?

I tried setting `IsPersonal` to false and `CacheTime` to `300` inside `InlineConfig`, but it didn't help.

**Comment by Syfaro** [comment]
I don't think this library has anything to do with those errors. I haven't seen them personally from my bots. 

If you can see something in the library that might be causing it let me know so I can reopen the issue though.
