### ISSUE TITLE
Missing ParseMode in helpers.go

### ISSUE THREAD

**Issue by anatoliyfedorenko** [go-telegram-bot-api/telegram-bot-api#192]
There is a need to add ParseMode: "Markdown" to line 18 in helpers.go because no ParseMode parameter is passed to function and therefore never bots will be able to send Markdown or HTML. This bug caused me several hours of stupidity when dealing with sending Markdown

**Comment by llitfkitfk** [comment]
```
msg := tgbotapi.NewMessage(chatID, text)
msg.ParseMode = "Markdown"
```
