### ISSUE TITLE
Please remove a few lines from readme or add a little comment

### ISSUE THREAD

**Issue by bardiarastin** [go-telegram-bot-api/telegram-bot-api#201]
Hello, tnx for awesome project
I'm building a bot using this repo,
I wanted to use CallbackQueries feature, everything was fine and I was able to send messages with inline button but I was not able to receive callbacks from telegram, searched the whole world from sky to earth and I was about to kill my self or use something else because of this three lines
```
if update.Message == nil {
	continue
}
```
It took about 3 hours to find out that new callback update is getting skipped cause it has no message
please add some comments or remove these 😭🤦🏻

**Comment by Syfaro** [comment]
Apologies for the unclear code! I'll add a comment about that.
