### ISSUE TITLE
Looping messages still exists on stable version 4.6.3

### ISSUE THREAD

**Issue by silence44** [go-telegram-bot-api/telegram-bot-api#203]
Please revert commit with update chan as you did it here:

https://github.com/go-telegram-bot-api/telegram-bot-api/commit/b60db1d2e17d88a92816d9ad3a49fd50da08ef87

Source with tag 4.6.3:
https://github.com/go-telegram-bot-api/telegram-bot-api/blob/e2f846d83a091384cafbbf817762de414d57b1f4/bot.go#L503

**Comment by Syfaro** [comment]
My apologies, I forgot that was tagged. v4.6.4 is now tagged with the fix.

https://github.com/go-telegram-bot-api/telegram-bot-api/releases/tag/v4.6.4
