### ISSUE TITLE
Strange behavior with xorm

### ISSUE THREAD

**Issue by skobkin** [go-telegram-bot-api/telegram-bot-api#204]
I've encountered very strange problem with xorm ORM and telegram-bot-api.

When I'm initializing Telegram API client xorm stops working.

Short example:

```go
// Success (row actually in the database)
database.AddUser(2, "test2")

bot, err := tgbotapi.NewBotAPI(os.Getenv("TELEGRAM_APITOKEN"))
if err != nil {
	log.Panic(err)
}

// Fail (no row in the database)
_, err = database.AddUser(3, "test3")
if err != nil {
	log.Panic(err)
}
```

Full example:

https://gist.github.com/skobkin/40e920686386c4614bbf744fffdf604d

**Comment by Syfaro** [comment]
![image](https://user-images.githubusercontent.com/1369709/48234928-4f912a00-e381-11e8-9a07-5eb5864cb794.png)

I can't replicate this on my Windows machine with go1.11 using go modules instead of dep (although I did have to move the `database.Sync` to above the first `database.AddUser` call).
