### ISSUE TITLE
Message is too long

### ISSUE THREAD

**Issue by xesai** [go-telegram-bot-api/telegram-bot-api#212]
Hello, does it possible to make auto split long messages? Got "message is too long" error so need to write additional check and split it. Thank you!

**Comment by Syfaro** [comment]
This is out of scope for this library I think. Splitting messages is a difficult task that can lead to unexpected behavior. Should it split at the maximum character mark? Or at a space, or a period? What should it do when a message is split, should it show it's one message out of multiple somehow, or add ellipsis? This either adds additional configuration or surprising defaults.
