### ISSUE TITLE
Telegram lock in Russia and proxy domain

### ISSUE THREAD

**Issue by nukassel** [go-telegram-bot-api/telegram-bot-api#213]
Hello! First of all I want to say thank you for this library! In Russia, api.telegram.org is not available. I have a proxy domain telegram.xyz.io. I can somehow indicate it so that all requests go exactly there?

**Comment by nukassel** [comment]
I would like to do without socks/http proxy

**Comment by zhuharev** [comment]
Now you can fork lib and change values here https://github.com/go-telegram-bot-api/telegram-bot-api/blob/898e79fe47dafa598b3f61dd570aa2921628e530/configs.go

**Comment by nukassel** [comment]
Может замутите какой нибудь сеттер, не очень хочется выкачавать библиотеку в папку ради переопределения одной строчки)

**Comment by zhuharev** [comment]
@nukassel ok, next release
