### ISSUE TITLE
Return MediaGroup messages

### ISSUE THREAD

**Issue by GooG2e** [go-telegram-bot-api/telegram-bot-api#215]
Hello!
I met problem that this API doesn't have method to send mediagroup and receive []Message.
Default Send method returns Message and there are no any other methods
Thank you!

**Comment by Syfaro** [comment]
Added in https://github.com/go-telegram-bot-api/telegram-bot-api/commit/fa4070825746d9c5c9d73bb37774a6ccc60fb80d
