### ISSUE TITLE
Telegram API result unmarshalling causes an error

### ISSUE THREAD

**Issue by Ekizare** [go-telegram-bot-api/telegram-bot-api#217]
There are some methods in Telegram API which returning just `True` on success (Ctrl+F -> `Returns True` at [docs](https://core.telegram.org/bots/api)). It is not a valid JSON object. [Send()](https://github.com/go-telegram-bot-api/telegram-bot-api/blob/fa4070825746d9c5c9d73bb37774a6ccc60fb80d/bot.go#L305) function tries to parse it and returning an unmarshalling error: 
`json: cannot unmarshal bool into Go value of type tgbotapi.Message`.
I am using `develop` branch with the latest commit.

Maybe it will be better to make another function for these calls, returning just boolean?

**Comment by Syfaro** [comment]
This is what the [Request](https://github.com/go-telegram-bot-api/telegram-bot-api/blob/fa4070825746d9c5c9d73bb37774a6ccc60fb80d/bot.go#L278) method is for.

**Comment by Ekizare** [comment]
Oh, really. Thanks!
