### ISSUE TITLE
NewBotAPI method return error

### ISSUE THREAD

**Issue by Necromantos** [go-telegram-bot-api/telegram-bot-api#224]
Error is: dial tcp 149.154.167.220:443: connectex: No connection could be made because the target machine actively refused it.
What i do wrong?

**Comment by zhuharev** [comment]
try enable VPN. If you try connect from Russia you under censorship.

**Comment by Syfaro** [comment]
This sounds like a connection issue which should be resolved with a proxy/VPN/something and not a problem with this library.
