### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by asminozhka** [go-telegram-bot-api/telegram-bot-api#232]
Please move to fasthttp https://github.com/valyala/fasthttp
Fasthttp works much better than net/http

**Comment by zhuharev** [comment]
I think this is over-engineering for bots app. Tell us about your experience, what you do not have enough CPU or memory?

**Comment by asminozhka** [comment]
> I think this is over-engineering for bots app. Tell us about your experience, what you do not have enough CPU or memory?

I'm always have enough CPU and I always need more memory

**Comment by lukaszraczylo** [comment]
It just means that your bot code is not optimised. I have my bot running on 1800+ groups at the same time and memory usage is 30mb.

**Comment by zhuharev** [comment]
@asminozhka you can avoid use http.Client if you setup server for receiving webhooks.

**Comment by zhuharev** [comment]
I close this issue because the migration to a new client is not planned.
