### ISSUE TITLE
Save user's input after bot's message

### ISSUE THREAD

**Issue by asminozhka** [go-telegram-bot-api/telegram-bot-api#233]
How can i catch user's input after sending a qestion?
```
User: /setinfo
Bot: How old are you?
User: I'm very old
Bot: Do you like Golang?
User: Yyeeaass!
Bot: Ok, this information was saved!
```
Thanks!

**Comment by asminozhka** [comment]
This might be helpful: https://hastebin.com/ejagazemic.go

**Comment by ArthurPatriot** [comment]
> This might be helpful: https://hastebin.com/ejagazemic.go

Link is broken.

**Comment by asminozhka** [comment]
@ArthurPatriot solution is to use "state machine". Just save user's state id in map, and check it on every new message.

**Comment by 1trackprojects1** [comment]
can someone help me with this? im stuck on it as well

**Comment by XOControl** [comment]
> can someone help me with this? im stuck on it as well

Did u solve this problem? I'm working on this issue now and I can't find information on the Internet(((

**Comment by omerxx** [comment]
To anyone reading this, I starting using FSM but ended up building my own using cache.
I went with redis and I'm saving `chat_id` as key and a set of `steps` in a menu that's changing when the user clicks.
I keep updating the value on redis with each click (catching the callback in the bot and check the state everytime). This is how I know in the middle of what flow the user is in, what is the next "menu" to send and whether they need to provide value / expect a result
