### ISSUE TITLE
How can I send multiple pictures at once?

### ISSUE THREAD

**Issue by zigitn** [go-telegram-bot-api/telegram-bot-api#234]
I am sorry to bother you, but I have not found a way to send multiple photos at once. Please help me.

**Comment by zigitn** [comment]
I mean, how to send album?

**Comment by zhuharev** [comment]
Just use [SendMeiaGroup](https://godoc.org/github.com/go-telegram-bot-api/telegram-bot-api#NewMediaGroup)

**Comment by mkhoussid** [comment]
> Just use [SendMeiaGroup](https://godoc.org/github.com/go-telegram-bot-api/telegram-bot-api#NewMediaGroup)

Should be noted, that `reply_markup` and, in my case, specifically `parse_mode` are unavailable with this approach

**Comment by kamil-alekber** [comment]
Is there a way to add caption and reply_markup with media group as of now?

**Comment by Unfantasy** [comment]
> 

set caption property only for the first element of an array

**Comment by Unfantasy** [comment]
> Is there a way to add caption and reply_markup with media group as of now?

set caption property only for the first element of an array

**Comment by yunlongw** [comment]
How can i SendMeiaGroup with text？

**Comment by Mehan-Ahmed** [comment]
> How can i SendMeiaGroup with text？

DM: @DevTanjed
