### ISSUE TITLE
ConversationHandler support? 

### ISSUE THREAD

**Issue by littlecxm** [go-telegram-bot-api/telegram-bot-api#239]
Want to build step by step conversation wizard bot like bot father.
![Snipaste_2019-05-30_13-45-49](https://user-images.githubusercontent.com/16154023/58611343-56619900-82e1-11e9-8cb7-6cc16e607fd5.png)
but how to determine context association and remember the current state,is there has any handler to handle it easy and light?use other session based solution(redis .etc) too heavy I think.

**Comment by Syfaro** [comment]
This is outside the scope of this library. For general discussion, I encourage you to take a look at the [Telegram group](https://telegram.me/go_telegram_bot_api) for this library.
