### ISSUE TITLE
Possibility to handle photo (or video) albums sent by user 

### ISSUE THREAD

**Issue by cherya** [go-telegram-bot-api/telegram-bot-api#242]
Is it possible to handle that user sent album (example below)? Now bot reacts to every photo or video in album like it's standalone message, not group. 

<img width="586" alt="telegram album example" src="https://user-images.githubusercontent.com/3810684/59611299-bd75af00-9123-11e9-9597-85e7d3871f77.png">

**Comment by Syfaro** [comment]
You should be able to use the [MediaGroupID](https://github.com/go-telegram-bot-api/telegram-bot-api/blob/develop/types.go#L149) to determine if all those photos are part of a single group.
