### ISSUE TITLE
HTTP proxy Error

### ISSUE THREAD

**Issue by taivy** [go-telegram-bot-api/telegram-bot-api#249]
Socks5 proxy and VPN work fine, but HTTP/HTTPS proxy doesn't.

When I create http client with proxy:
proxyUrl, err := url.Parse("http_proxy_here")
client := &http.Client{Transport: &http.Transport{Proxy: http.ProxyURL(proxyUrl)}}
And pass it to NewBotAPIWithClient, I get error 
Post "https://api.telegram.org/botMY_TOKEN/getMe": Found
It doesn't look like error (302 Found response isn't error), but Go panics and response is nil.

**Comment by Syfaro** [comment]
A 302 is not the correct response for the getMe endpoint, I assume the proxy is doing something weird.
