### ISSUE TITLE
video info nil in updates

### ISSUE THREAD

**Issue by johnbalvin** [go-telegram-bot-api/telegram-bot-api#255]
I have this similar code as the example in README

```
for update := range updates {
     if update.ChannelPost != nil {
            msg := update.ChannelPost
            if strings.Contains(msg.Document.MimeType, "video") {
                    //msg.Video  <- it's nil 
            }
       }
}
```
When user uploads video to channel, the video info it's nil

**Comment by Syfaro** [comment]
Videos and documents are mutually exclusive. Documents are files sent as-is, videos are re-encoded for support on all platforms and fast viewing.
