### ISSUE TITLE
Serverless - Expose hanlder methods to support functions as a service

### ISSUE THREAD

**Issue by phrozen** [go-telegram-bot-api/telegram-bot-api#260]
Hi, I've been working with Telegram bots on Node.js and I would love to port most of them to Go, but the most common scenario I have right now is deploying Serverless Bots with Webhook updates. Most serverless platforms (AWS Lambda, Google Cloud Functions, Azure Functions, etc...) adhere to Go's std lib and expect an exposed `Handler func(res http.ResponseWriter, req *http.Request)` and although this library is using exactly that internally, there is no exposure to a sort of HandleUpdate method alone based on a request/response pair to support any serverless platform.

The idea is mainly to expose a method `bot.HandleUpdate( res http.ResponseWriter, req *http.Request)` to do the same internal stuff the library is doing while listening to the webhook  to handle a single update.

**Comment by Syfaro** [comment]
This seems like a reasonable idea, I'd be happy to accept a PR for this.

The library does no handling on the request besides reading the body into an `Update` though.

**Comment by phrozen** [comment]
> This seems like a reasonable idea, I'd be happy to accept a PR for this.

Perfect! Let me see what I can do.

> The library does no handling on the request besides reading the body into an Update though.

Exactly! I just need to expose a way to make the engine run for a single `Update` every time without going through the server's listening logic.
