### ISSUE TITLE
panic: runtime error: when trying to detect video

### ISSUE THREAD

**Issue by Invy55** [go-telegram-bot-api/telegram-bot-api#262]
Hi, I get this error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x68c434]

goroutine 1 [running]:
main.main()
        /---/----/----.go:146 +0x644
exit status 2
```
when i try to detect a video and resend it to the reply user. The code I used is the example modified ( [Aviaible here](https://pastebin.com/hhdvhD8s) ).

**Comment by Syfaro** [comment]
I can't see how line 146 in that file is doing anything with videos. 

In general, you need to assert that pointers are not nil before using them. Please let me know if this issue needs to be reopened, but it appears to be an issue not related to this library.

**Comment by Invy55** [comment]
Can you, please, explain me how can I do that?

**Comment by Invy55** [comment]
> I can't see how line 146 in that file is doing anything with videos.
> 
> In general, you need to assert that pointers are not nil before using them. Please let me know if this issue needs to be reopened, but it appears to be an issue not related to this library.

Can you, please, explain me how can I do that?
