### ISSUE TITLE
Get MessageID after Send()

### ISSUE THREAD

**Issue by crackhd** [go-telegram-bot-api/telegram-bot-api#272]
```go
		msg := tgbotapi.NewMessage(update.Message.Chat.ID, update.Message.Text)
                bot.Send(msg)
```

How do I get MessageID after this code? I do not see any solution in existing issues or Readme examples.

**Comment by IzeBerg** [comment]
if message, err := bot.Send(message); err == nil {
	//message.MessageID
}
