### ISSUE TITLE
reply_markup in Message

### ISSUE THREAD

**Issue by guestl** [go-telegram-bot-api/telegram-bot-api#278]
In the Telegram API description there is the field "reply_markup" with InlineKeyboardMarkup type.  However, there is no any reply_markup in types.go file in the Message struct.

Is that possible to add "reply_markup" in the Message struct?

**Comment by Syfaro** [comment]
This is on develop.

https://github.com/go-telegram-bot-api/telegram-bot-api/blob/5b3f2f3/types.go#L205
