### ISSUE TITLE
Bot returns URL error

### ISSUE THREAD

**Issue by utdrmac** [go-telegram-bot-api/telegram-bot-api#280]
I have this in our code:
```
if _, err := bot.Send(msg); err != nil {
	botErr := err.(tbot.Error)
	log.WithFields(log.Fields{
		"Code": botErr.Code, "Message": botErr.Message, "ChatId": chatId,
	}).Error("Bot Response Error")
}
```

And the other day, had this happen:
`ERRO[96770] Panic Recovered in main loop:interface conversion: error is *url.Error, not tgbotapi.Error`

What is the correct way to decode/handle error messages from the bot? The particular issue that keeps coming up with us is "403 Forbidden User has blocked bot" and I'm trying to figure out which user that is so I can delete them from our backend database.

Is there some way to handle both bot error and http/url error? Should the bot be wrapping http errors into bot errors?

**Comment by Syfaro** [comment]
One strategy would be to switch on the error type.

As of the current master version, all 'normal' errors (not caused by network errors or downtime) should return a `tgbotapi.Error` which would include the status code and description of the error.
