### ISSUE TITLE
Problem with a non-working proxy

### ISSUE THREAD

**Issue by istokin** [go-telegram-bot-api/telegram-bot-api#289]
Good afternoon!
I need to know that an error occurred in the condition of the "GetUpdatesChan" function. Otherwise, when using a proxy, there is no way to determine if the current proxy is working or you need to change the proxy.

Tell me how to implement this. At the moment, the problem is here:
updates, err: = bot.GetUpdates (config) // there is no access to this error from my code.
if err! = nil {
log.Println (err)
log.Println ("Failed to get updates, retrying in 3 seconds ...")
time.Sleep (time.Second * 3)

continue

**Comment by markgenuine** [comment]
Hello, add use proxy into bot.go and all will be work. But you mast make change:
`package tgbotapi

import (
.............
"golang.org/x/net/proxy"
)
..................
func NewBotAPI(token string) (*BotAPI, error) {

	att := &proxy.Auth{%Login%, %Password%}
	dialSocks5, err := proxy.SOCKS5("tcp", %ip:port%, att, proxy.Direct)
	if err != nil {
		fmt.Println(err)
	}

	transport := &http.Transport{Dial: dialSocks5.Dial}
	client := &http.Client{}
	client.Transport = transport

	return NewBotAPIWithClient(token, client)
}
........
`

**Comment by Syfaro** [comment]
You can implement your own variant of `GetUpdatesChan` with custom error handling, the whole method is very simple. 

https://github.com/go-telegram-bot-api/telegram-bot-api/blob/8717c40/bot.go#L508-L540
