### ISSUE TITLE
getUpdates' response, has not contain the mention user's user_id value

### ISSUE THREAD

**Issue by af913337456** [go-telegram-bot-api/telegram-bot-api#293]
command msg:       /tip amount coin @specerxi

response: 

```json
{"update_id":736079402,"message":{"message_id":189,"from":{"id":894669391,"first_name":"lin","last_name":"guanhong","username":"ghost_lin","language_code":"zh-hans","is_bot":false},"date":1578310296,"chat":{"id":-384477687,"type":"group","title":"BlockABC Team","username":"","first_name":"","last_name":"","all_members_are_administrators":true,"photo":null},"forward_from":null,"forward_from_chat":null,"forward_from_message_id":0,"forward_date":0,"reply_to_message":null,"edit_date":0,"text":"@specerxi","entities":[{"type":"mention","offset":0,"length":9,"url":"","user":null}],...
```

as you see, the user object in entities is null !!!!!

what the hell?

**Comment by Syfaro** [comment]
Telegram docs suggest this is normal behavior.

> Optional. For “text_mention” only, the mentioned user

As it’s a typical ‘mention’ entity, the user isn’t expected to be there.

**Comment by af913337456** [comment]
@Syfaro but the username text can be change on telegram client app, how can we use this thing to represent uniqueness? that is bad for our bot program, right?

**Comment by af913337456** [comment]
@Syfaro The robot program needs a field that can uniquely identify the user and will not be modified, such as user_id. @overplumbum @robx @treeder

**Comment by af913337456** [comment]
@Syfaro So there is absolutely no another way to get a user's id by his username?

**Comment by Syfaro** [comment]
I've run into this issue too, but I haven't found a way around it yet. 

I'm closing this issue as it's out of scope for this project though.

**Comment by af913337456** [comment]
@Syfaro my bot project It's over. it kill me !!!
