### ISSUE TITLE
Send bot commands with Inline Keyboard

### ISSUE THREAD

**Issue by barricade86** [go-telegram-bot-api/telegram-bot-api#295]
Is there any possibility to send bot commans, using InlineKeyboard? For example, i want create something like below:
`tgbotapi.NewInlineKeyboardMarkup(
     tgbotapi.NewInlineKeyboardRow(
		tgbotapi.NewInlineKeyboardButtonData("4","/some_cmd"),		
    ),
)`

And when i press the button, i could be handle such update as bot command
`              
               if update.CallbackQuery.Message.IsCommand(){
                 //do something
              }
`
Is there any possibility?

**Comment by msergo** [comment]
yes, you have to set **ReplyMarkup** property of the message, you are going to send

**Comment by barricade86** [comment]
@msergo And how i should do that? Could you provide the example value for my issue?

**Comment by msergo** [comment]
So, you are creating a button with some data, which will be passed as a callback
`tgbotapi.NewInlineKeyboardButtonData("Button 4 text","callback_4_data")`
Then once the button pressed, you will get this data on the `update` e.g.
`update.CallbackQuery.Data // "callback_4_data"`

**Comment by andig** [comment]
Similar question marks here. This doesn't seem to work and requires a message text (and only that is displayed):

	if strings.ToLower(update.Message.Text) == "/mode" {
		ikm := tgbotapi.NewInlineKeyboardMarkup(
			tgbotapi.NewInlineKeyboardRow(
				tgbotapi.NewInlineKeyboardButtonData("Off", "off"),
				tgbotapi.NewInlineKeyboardButtonData("Now", "now"),
				tgbotapi.NewInlineKeyboardButtonData("Min", "min"),
				tgbotapi.NewInlineKeyboardButtonData("PV", "pv"),
			),
		)

		msg := tgbotapi.NewMessage(update.Message.Chat.ID, "foo")
		msg.ReplyMarkup = tgbotapi.NewEditMessageReplyMarkup(update.Message.Chat.ID, update.Message.MessageID, ikm)
		if _, err := m.bot.Send(msg); err != nil {
			log.ERROR.Print(err)
		}
	}

An example how to reply with keyboard markup would be most helpful.
