### ISSUE TITLE
tgbotapi.NewWebhook ignores error on invalid url

### ISSUE THREAD

**Issue by kortov** [go-telegram-bot-api/telegram-bot-api#311]
Here's an error is ignored
https://github.com/go-telegram-bot-api/telegram-bot-api/blob/aa124ef1e84ecc14654ad242f3cf3bd2b0d5956c/helpers.go#L394-L400

so when you pass an url like `"https://example.com" + bot.Token` here (and I think it's easy to do such mistake)
https://github.com/go-telegram-bot-api/telegram-bot-api/blob/aa124ef1e84ecc14654ad242f3cf3bd2b0d5956c/bot_test.go#L490

the test (and bot of course) fails with this
```
=== RUN   TestSetWebhookWithoutCert
2020/02/29 22:51:04 setWebhook resp: {"ok":true,"result":true,"description":"Webhook is already deleted"}
--- FAIL: TestSetWebhookWithoutCert (2.83s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5d6e4a]

goroutine 6 [running]:
testing.tRunner.func1(0xc0000e4100)
	/snap/go/5364/src/testing/testing.go:874 +0x3a3
panic(0x71b060, 0x9fd7f0)
	/snap/go/5364/src/runtime/panic.go:679 +0x1b2
net/url.(*URL).String(0x0, 0xc000001980, 0x300000002)
	/snap/go/5364/src/net/url/url.go:775 +0x4a
github.com/go-telegram-bot-api/telegram-bot-api.(*BotAPI).SetWebhook(0xc0000ea000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/user/GolandProjects/telegram-bot-api/bot.go:454 +0x3c8
github.com/go-telegram-bot-api/telegram-bot-api_test.TestSetWebhookWithoutCert(0xc0000e4100)
	/home/user/GolandProjects/telegram-bot-api/bot_test.go:491 +0x15d
testing.tRunner(0xc0000e4100, 0x799998)
	/snap/go/5364/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/snap/go/5364/src/testing/testing.go:960 +0x350

Process finished with exit code 1
```

**Comment by ErrorBoi** [comment]
I've figured out, that error occurs, when program is trying to parse given URL (like `"https://example.com" + bot.Token`) in `NewWebhook()` or `NewWebhookWithCert()`.

It fails, because bot token contains a colon and parser suggests, that part after colon is port.
My proposal is to handle error from `url.Parse()` instead of ingoring it, and if `err != nil`, return empty `WebhookConfig`.

According tests should fail with custom error, if `Webhook.URL == nil`.

**Comment by ErrorBoi** [comment]
Fixed this issue and created [pull request](https://github.com/go-telegram-bot-api/telegram-bot-api/pull/320), made in accordance with my plan in comment above. Please let me know if solution is not proper, I will fix it.

**Comment by Syfaro** [comment]
Given that panics should generally be avoided, it would be a good idea to return the error. 

There's already a few breaking changes in v5 for correctness reasons, adding another wouldn't be so bad.

**Comment by Syfaro** [comment]
`NewWebhook` now returns an error.

https://github.com/go-telegram-bot-api/telegram-bot-api/blob/2a2f7c5083cf35ab2b6ca69d37ee23d88f310e15/helpers.go#L300-L303
