### ISSUE TITLE
Error on Send chattable when perform sendChatAction

### ISSUE THREAD

**Issue by temamagic** [go-telegram-bot-api/telegram-bot-api#314]
When using sendChatAction, on https://github.com/go-telegram-bot-api/telegram-bot-api/blob/develop/bot.go#L314 line json marshal try to unmarhal "true" to message struct

![image](https://user-images.githubusercontent.com/15264697/76021050-9b33f380-5f35-11ea-8ff1-6ee250488645.png)

**Comment by temamagic** [comment]
I don't know, how is better, but simple
```
resultStr := string(resp.Result)
	if resultStr != "true" {
		err = json.Unmarshal(resp.Result, &message)
	}
```
can fix it.

Can't send new PR cuz i have already one PR, and some feature maybe you think useless :)

**Comment by Syfaro** [comment]
On develop, you should use [`Request`](https://github.com/go-telegram-bot-api/telegram-bot-api/blob/develop/bot.go#L287) for requests that don't return a `Message` response. In the case of `sendChatAction`, the only possible non-error return value is true, so there's no point in parsing it.
