### ISSUE TITLE
go.mod?

### ISSUE THREAD

**Issue by Feresey** [go-telegram-bot-api/telegram-bot-api#315]
Why there are no go.mod in your repository?

**Comment by kortov** [comment]
a good question, but the PR is here #274

**Comment by Feresey** [comment]
Why PR has not been accepted?

**Comment by kortov** [comment]
I dunno, the repo has a strange status : it's maintained, but it's not. There is an old issue about it it and there are no answers #122 . Maybe you or someone could get an answer about a project, I don't like when popular repos become stale. Maybe someone can answer here https://telegram.me/go_telegram_bot_api

**Comment by doncote** [comment]
Anyone have an opinion on this package vs https://github.com/tucnak/telebot ?

Looks like telebot is more actively maintained.

**Comment by zhuharev** [comment]
merged #274
