### ISSUE TITLE
how can i receive another bot's msg when my bot with it in a same group

### ISSUE THREAD

**Issue by af913337456** [go-telegram-bot-api/telegram-bot-api#316]
i found a problem, that is my bot can't receiver another bot's msg. and we are in a same group.

**Comment by af913337456** [comment]
@Syfaro hi big guy, can you help me, thanks

**Comment by Syfaro** [comment]
> Bots talking to each other could potentially get stuck in unwelcome loops. To avoid this, we decided that bots will not be able to see messages from other bots regardless of mode.

https://core.telegram.org/bots/faq#why-doesnt-my-bot-see-messages-from-other-bots
