### ISSUE TITLE
Not supported field Caption Entities

### ISSUE THREAD

**Issue by b2r2** [go-telegram-bot-api/telegram-bot-api#323]
I use v4.6.4 I can't use the Caption Entities field(https://core.telegram.org/bots/api#message)  because this field is not available in this version

**Comment by Syfaro** [comment]
It is part of develop, which will be merged soon.

https://github.com/go-telegram-bot-api/telegram-bot-api/blob/5b3f2f33656b21a1eb02a0711cdc57a01981eedb/types.go#L174
