### ISSUE TITLE
Can't use my own Chattable structures because of privates methods in there

### ISSUE THREAD

**Issue by oleg-raev** [go-telegram-bot-api/telegram-bot-api#329]
Please, make Chattable interface more friendly for the library clients:
```
// Chattable is any config type that can be sent.
type Chattable interface {
	Values() (url.Values, error)
	Method() string
}
```

Currently, Telegram bot has many methods that are not implemented in your library.

**Comment by Syfaro** [comment]
I believe everything is currently implemented in the develop branch. But it would probably be good to make the methods public anyway. This will likely be changed for v5.

**Comment by Syfaro** [comment]
Can be reopened if there's further interest, but I'm going to leave them private for now.
