### ISSUE TITLE
cannot access some methods when using with go.mod

### ISSUE THREAD

**Issue by phanirithvij** [go-telegram-bot-api/telegram-bot-api#332]
It works fine when not using go.mod

my `go.mod`

```go
module github.com/phanirithvij/stickerbot

go 1.13

require (
	github.com/cavaliercoder/grab v2.0.0+incompatible
	github.com/go-telegram-bot-api/telegram-bot-api v4.6.4+incompatible
	github.com/spf13/viper v1.6.3
	github.com/technoweenie/multipartstreamer v1.0.1 // indirect
)
```

my `go.sum` file
```go
//...
github.com/go-telegram-bot-api/telegram-bot-api v4.6.4+incompatible h1:2cauKuaELYAEARXRkq2LrJ0yDDv1rW7+wrTEdVL3uaU=
github.com/go-telegram-bot-api/telegram-bot-api v4.6.4+incompatible/go.mod h1:qf9acutJ8cwBUhm1bqgz6Bei9/C/c93FPDljKWwsOgM=
```

Code:

```go
//...
config := tgbotapi.GetStickerSetConfig{Name: stickerSet}
data, err := bot.GetStickerSet(config)
//...
```

Error:
```go
# command-line-arguments
.\bot.go:76:14: undefined: tgbotapi.GetStickerSetConfig
.\bot.go:77:20: bot.GetStickerSet undefined (type *tgbotapi.BotAPI has no field or method GetStickerSet)
```

**Comment by mikeee** [comment]
You're importing the v4 module, I sanity checked the tags and it appears that the method you're referencing `GetStickerSetConfig` and it's only implemented in the tagged v5.

Grab the updated module using:  
```
go get -u github.com/go-telegram-bot-api/telegram-bot-api/v5
```

When using Go Modules you're referencing the package at a particular point in time that has been 'tagged'.

**Comment by phanirithvij** [comment]
Even with v5 I get an error saying the version name formating is not
standard when using with go modules. It shouldn't be 5.x.x. but 1.x.x. I'll
update the exact error here.

**Comment by phanirithvij** [comment]
Other errors when using `/v5` are
```go
.\bot.go:110:7: bot.AnswerCallbackQuery undefined (type *tgbotapi.BotAPI has no field or method AnswerCallbackQuery)
.\bot.go:140:14: undefined: tgbotapi.NewInlineQueryResultCachedSticker
.\bot.go:161:21: bot.AnswerInlineQuery undefined (type *tgbotapi.BotAPI has no field or method AnswerInlineQuery)
.\bot.go:323:10: data.IsAnimated undefined (type tgbotapi.StickerSet has no field or method IsAnimated)
.\bot.go:336:19: bot.DeleteMessage undefined (type *tgbotapi.BotAPI has no field or method DeleteMessage)
.\bot.go:355:20: bot.DeleteMessage undefined (type *tgbotapi.BotAPI has no field or method DeleteMessage)
```

**Comment by mikeee** [comment]
You're jumping between different packages, v5 has many breaking changes - it has removed some of the methods or fields which you are attempting to reference from v4.

Refer to the v5 documentation: https://pkg.go.dev/github.com/go-telegram-bot-api/telegram-bot-api/v5?tab=doc

**Comment by phanirithvij** [comment]
Why were those methods removed?

**Comment by mikeee** [comment]
https://telegram.me/go_telegram_bot_api
Try joining the group, you'll probably have the best luck finding the answers you're looking for there. 

*when I said removed it also could mean any modification at all, `NewInlineQueryResultCachedSticker` for example wasn't and still isn't merged afaik.

**Comment by Syfaro** [comment]
A number of methods were removed because they were either useless (no specific return type) or incorrect (ignoring parsing errors). 

More detailed info about the breaking changes are available here: https://go-telegram-bot-api.github.io/migrating-from-v4/

There's a few things not currently available on v5 which still need to get merged in before release.

**Comment by smir45** [comment]
HELP
whenever i perform 
go get -u github.com/go-telegram-bot-api/telegram-bot-api/v5  this command i got a error saying 

go get: module github.com/go-telegram-bot-api/telegram-bot-api@upgrade found (v4.6.4+incompatible), but does not contain package github.com/go-telegram-bot-api/telegram-bot-api/v5

any solutions?

**Comment by werdnum** [comment]
Unfortunately the link above, "https://go-telegram-bot-api.github.io/migrating-from-v4/", is dead.

Is it possible that 'AnswerCallbackQuery' is one of those things that is not currently available on v5? It seems unlikely, since [the relevant line of code](https://github.com/go-telegram-bot-api/telegram-bot-api/blame/54104a08f947e08c460c45d195076e48e61f0a26/bot.go#L615) has been there for 6 years. But somehow it's not appearing in godoc and I do get a compile error.

**Comment by yshym** [comment]
Anyone, who experience this issue, check [the example of using the InlineConfig type](https://pkg.go.dev/github.com/go-telegram-bot-api/telegram-bot-api/v5#example-InlineConfig)
