### ISSUE TITLE
NewVideoUpload more 10mb

### ISSUE THREAD

**Issue by sifaaa** [go-telegram-bot-api/telegram-bot-api#334]
When I send a video less than 10 mb it looks good

![image](https://user-images.githubusercontent.com/49375187/81501064-dad4de00-92de-11ea-9b6b-8092a09ded21.png)

When I send a video more than 10 mb it looks bad

![image](https://user-images.githubusercontent.com/49375187/81501073-ef18db00-92de-11ea-8741-5b88932eff42.png)

the video turns into a file, can I fix it?

I use google translator

**Comment by sifaaa** [comment]
I use
msg := tgbotapi.NewVideoUpload(update.Message.Chat.ID, "./video2.mp4")
bot.Send(msg)

is there any other method for sending large videos?

**Comment by Syfaro** [comment]
You should be able to upload videos up to 50MB: https://core.telegram.org/bots/api#sendvideo

Are you sure the larger video file is encoded in a format Telegram understands?
