### ISSUE TITLE
update.CallbackQuery content

### ISSUE THREAD

**Issue by a-frony** [go-telegram-bot-api/telegram-bot-api#341]
It will be great if update.CallbackQuery object can contain replyMarkup slice. You need it to modify inline keyboard, for example to do like/dislike. Now we have to create new keyboard instead of modifiing old one. When you click inline button response JSON from Telegram contains keyboard already, so why we cannot use it?

**Comment by Syfaro** [comment]
It looks like the `Message` field on the `CallbackQuery` should still contain the reply markup. 

Otherwise, there's nothing this library can do to add features to Telegram.
