### ISSUE TITLE
Button in chat bot only and loginUrl

### ISSUE THREAD

**Issue by Luksssss** [go-telegram-bot-api/telegram-bot-api#342]
Hi, how can I send in chat bot a button only (without text message)?

I try to do it like this but it doesn’t work:

```
    myBut := tgbotapi.NewInlineKeyboardMarkup(
    	tgbotapi.NewInlineKeyboardRow(
    		tgbotapi.NewInlineKeyboardButtonURL("Link", Site),
    	),
    )
    
    msg.ChatID = *fromID
    msg.ReplyMarkup = myBut
    
    bot.Send(msg)
```

And does that API allow to get **login_url**?
[Telegram API inlinekeyboardbutton](
https://core.telegram.org/bots/api#inlinekeyboardbutton)

Thanks!

**Comment by Syfaro** [comment]
I don't believe it's possible to send an empty message.

You can work with logins using the develop branch, https://github.com/go-telegram-bot-api/telegram-bot-api/blob/5b3f2f33656b21a1eb02a0711cdc57a01981eedb/types.go#L579
