### ISSUE TITLE
closes when a message in the channel

### ISSUE THREAD

**Issue by sifaaa** [go-telegram-bot-api/telegram-bot-api#343]
Used search and tried solutions, did not help
Can I exclude messages from the channel?

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x48 pc=0x7309fc]

I use google translator

**Comment by Syfaro** [comment]
It looks like you're trying to access something that's nil. It's possible you're getting other updates instead of the type you're looking for.
