### ISSUE TITLE
sendMediaGroup empty result 

### ISSUE THREAD

**Issue by PerfilovStanislav** [go-telegram-bot-api/telegram-bot-api#348]
`func (bot *BotAPI) makeMessageRequest`
change `var message Message` to `var message []Message`

**Comment by Syfaro** [comment]
This fix is on develop. 

https://github.com/go-telegram-bot-api/telegram-bot-api/blob/75e27e1380817b6d09f88cb9780eaa2804927840/bot.go#L320-L333
