### ISSUE TITLE
Sending GIFs

### ISSUE THREAD

**Issue by Rukenshia** [go-telegram-bot-api/telegram-bot-api#35]
Is there any way to send GIFs via this package right now? I tried using tgbotapi.NewPhotoUpload but this is just sending a normal image.

**Comment by Rukenshia** [comment]
Just figured it out right now. They can be send with "NewDocumentUpload". Maybe it is a good idea to put this into the documentation as well.

**Comment by Syfaro** [comment]
Telegram did not do a good job with that, I'll add it to the docs now.
