### ISSUE TITLE
is possible to replace document?

### ISSUE THREAD

**Issue by e1z0** [go-telegram-bot-api/telegram-bot-api#350]
Is it possible somehow to replace document (the movie clips sent before replace with new ones) ?

**Comment by Syfaro** [comment]
Yes, you can use the `editMessageMedia` method to replace documents, videos, etc.

It's currently only available on develop: https://github.com/go-telegram-bot-api/telegram-bot-api/blob/774f1e72e7647a5e78d4d3345f54581249bbf110/configs.go#L684-L689
