### ISSUE TITLE
Support uploading multiple files in a single request

### ISSUE THREAD

**Issue by Syfaro** [go-telegram-bot-api/telegram-bot-api#354]
Certain methods (sendMediaGroup, editMessageMedia, anything that supports thumbnails) allow uploading multiple files. Currently, `UploadFile` is structured in such a way it can only accept a single file to upload: https://github.com/go-telegram-bot-api/telegram-bot-api/blob/da98517cd2d9897e9cff6ee365b65fa9a41e3ae5/bot.go#L151-L159

Therefore, there needs to be a change to support uploading multiple files. One blocking issue is that the underlying library used to send files without reading everything into memory, [multipartstreamer](https://github.com/technoweenie/multipartstreamer), only accepts one file per request. A replacement would have to be created.

I would love to get feedback on the best way to implement this.

**Comment by HirbodBehnam** [comment]
Hello!
Before reading my comment keep in mind that I'm really noob.
I suggest using [io.pipe](https://golang.org/pkg/io/#Pipe) with [mime/multipart](https://golang.org/pkg/mime/multipart/) and [io.copy](https://golang.org/pkg/io/#Copy) to upload your files with minimal ram usage. (The buffer size of io.Copy is 32KB)
Here is a small code sample I write for multi-file uploads with comments on most of the lines to explain what is going on:
https://gist.github.com/HirbodBehnam/d0344f2377cbcd96bc058f31360a7658
I hope it helps

**Comment by Syfaro** [comment]
Hi @HirbodBehnam, thank you for the code sample! That seems like a great strategy for doing multiple uploads. 

However, because it involved a rather large internal change to get it into a good condition, I implemented it myself. I left a comment crediting you for your contribution though, I hope that's okay. https://github.com/go-telegram-bot-api/telegram-bot-api/blob/ce4fc988c916518bf64e8d02be6e19d89d745928/bot.go#L155-L221

**Comment by HirbodBehnam** [comment]
Hello again
That's 100% fine with me!
I'm glad I helped
