### ISSUE TITLE
Answering inline query with a sticker

### ISSUE THREAD

**Issue by yevhenshymotiuk** [go-telegram-bot-api/telegram-bot-api#361]
I want to use `InlineQueryResultCachedSticker`/`NewInlineQueryResultCachedSticker` in my project. As far as i understand, it is not available in current release. So, i'd like to know, if there is any way to use it now or when it will be available.

**Comment by tjhorner** [comment]
It seems to be available in the current release:

https://github.com/go-telegram-bot-api/telegram-bot-api/blob/7a018ae8739bcd25eeb220a85c35bf1ad73e1da8/types.go#L756-L764

**Comment by yevhenshymotiuk** [comment]
@tjhorner here is what i have in my `go.mod`: `github.com/go-telegram-bot-api/telegram-bot-api v4.6.4+incompatible`. `InlineQueryResultCachedSticker` and `NewInlineQueryResultCachedSticker` are undefined

**Comment by tjhorner** [comment]
Oh that is a very old version, last commit is from 2018. Versioning is kind of a mess right now; you might want to just reference `master` until it's all figured out.

**Comment by yevhenshymotiuk** [comment]
Do `go modules` provide functionality for referencing specific branch or it is only available while using `go get`?

**Comment by yevhenshymotiuk** [comment]
Oh, i see it. I can just write it in `go.mod` file instead of tag

**Comment by yevhenshymotiuk** [comment]
Now everything seems to be fine. Thx for your help

**Comment by yevhenshymotiuk** [comment]
I should admit that we have to add `replace github.com/go-telegram-bot-api/telegram-bot-api => github.com/go-telegram-bot-api/telegram-bot-api master` to our `go.mod` file. Otherwise this file will be rewritten back every time `gopls` check import statements or you rebuild an app
