### ISSUE TITLE
Is it possible to run this alongside an HTTP server?

### ISSUE THREAD

**Issue by Snazzyham** [go-telegram-bot-api/telegram-bot-api#362]
Apologies if this is a little confusing, but let me try to explain what I'm trying to achieve. 

I have a REST API that currently does some processing for a SaaS app. We want to use Telegram for notifications. I want to be able to set this up so that the bot server is listening for POST requests on say `/notification` and then pass that on to the bot, say using something like `bot.NewMessage(chatId, messageBody)` 

Would something like that be possible with this library? 

Thanks in advance.

**Comment by tjhorner** [comment]
If I am understanding you correctly, you have some other source sending events to `POST /notification`, and you want the bot to send a message to a Telegram user in response? That is definitely possible. You could do something like this (I didn't test it, so treat it like pseudocode):

```golang
bot, _ := tgbotapi.NewBotAPI("YourBotToken")

http.HandleFunc("/notification", func(w http.ResponseWriter, r *http.Request) {
	// Parse the data, or whatever
	msg := tgbotapi.NewMessage(12345, "Message text")
	bot.Send(msg)

	w.WriteHeader(200)
})
```

**Comment by tjhorner** [comment]
Assuming this was resolved... closing. Let me know if you need any more help.
