### ISSUE TITLE
ChatMember Title is missing.

### ISSUE THREAD

**Issue by himynameisulpa** [go-telegram-bot-api/telegram-bot-api#363]
Hi, 
https://godoc.org/github.com/go-telegram-bot-api/telegram-bot-api#ChatMember I need to use the title attribute.
the python library has it: https://python-telegram-bot.readthedocs.io/en/stable/telegram.chatmember.html#telegram.ChatMember
I hope, i can use it soon.

**Comment by tjhorner** [comment]
Thanks for bringing this up. I created #364 to address this. You can use the `chatmember-custom-title` branch in the meantime.

**Comment by tjhorner** [comment]
@himynameisulpa The `CustomTitle` field is now available on `ChatMember`.

**Comment by himynameisulpa** [comment]
thanks
