### ISSUE TITLE
answering inline query

### ISSUE THREAD

**Issue by pyed** [go-telegram-bot-api/telegram-bot-api#37]
I think that we need an example of answering inline-query, I'm having a little problem making one myself, so hopefully the following code will demonstrate a question/example to be used in `README.md`
```go
package main

import (
	"log"

	"gopkg.in/telegram-bot-api.v1"
)

func main() {
	bot, err := tgbotapi.NewBotAPI("MyAwesomeBotToken")
	if err != nil {
		log.Panic(err)
	}

	log.Printf("Authorized on account %s", bot.Self.UserName)

	u := tgbotapi.NewUpdate(0)
	u.Timeout = 60

	updates, err := bot.GetUpdatesChan(u)

	for update := range updates {
		if update.InlineQuery.Query == "" {
			continue
		}

		answer := tgbotapi.InlineQueryResultArticle{
			InlineQueryResult: tgbotapi.InlineQueryResult{ // ??
				Type: "article",
				ID:   update.InlineQuery.ID,
			},

			Title:       "Echo",
			MessageText: update.InlineQuery.Query,
		}

		inlineConf := tgbotapi.InlineConfig{
			InlineQueryID: update.InlineQuery.Query,
			Results:       []tgbotapi.InlineQueryResult{answer.InlineQueryResult}, // ??
		}

		if _, err := bot.AnswerInlineQuery(inlineConf); err != nil {
			log.Println(err)
		}

	}
}
```
I'm not sure how to deal with `InlineQueryResult`, this example will hit this error: `[Error]: Bad request: Can't find field "message_text"`

**Comment by Syfaro** [comment]
I'm doing something like the following:

```go
var results []interface{}

for _, event := range events {
    article := tgbotapi.NewInlineQueryResultArticle(event.ID, event.Title, event.Body)
    article.Description = event.Description

   results = append(results, article)
}

inline := tgbotapi.InlineConfig{
    InlineQueryID: inlineQuery.ID,
    IsPersonal: true,
    CacheTime: 0,
    Results: results,
}

_, err := f.API.AnswerInlineQuery(inline)
```

**Comment by pyed** [comment]
okay, how come this is still not working for me ? same error

```go
package main

import (
	"log"

	"gopkg.in/telegram-bot-api.v2"
)

func main() {
	bot, err := tgbotapi.NewBotAPI("147016571:AAFRLidnanGm8jvLyhsFnnNBL3DhkpmPk08")
	if err != nil {
		log.Panic(err)
	}

	log.Printf("Authorized on account %s", bot.Self.UserName)

	u := tgbotapi.NewUpdate(0)
	u.Timeout = 60

	updates, err := bot.GetUpdatesChan(u)

	for update := range updates {
		if update.InlineQuery.Query == "" {
			continue
		}

		article := tgbotapi.NewInlineQueryResultArticle(update.InlineQuery.ID, "Echo", update.Message.Text)

		inlineConf := tgbotapi.InlineConfig{
			InlineQueryID: update.InlineQuery.ID,
			IsPersonal:    true,
			CacheTime:     0,
			Results:       []interface{}{article},
		}

		if _, err := bot.AnswerInlineQuery(inlineConf); err != nil {
			log.Println(err)
		}
	}
}
```

**Comment by Syfaro** [comment]
Inline queries don't show the text in the message, you want `update.InlineQuery.Query`.

**Comment by pyed** [comment]
aaah, I must've been too sleepy while trying that, now this works

```go
package main

import (
    "log"

    "gopkg.in/telegram-bot-api.v2"
)

func main() {
    bot, err := tgbotapi.NewBotAPI("MyAwesomeBotToken")
    if err != nil {
        log.Panic(err)
    }

    log.Printf("Authorized on account %s", bot.Self.UserName)

    u := tgbotapi.NewUpdate(0)
    u.Timeout = 60

    updates, err := bot.GetUpdatesChan(u)

    for update := range updates {
        if update.InlineQuery.Query == "" {
            continue
        }

        article := tgbotapi.NewInlineQueryResultArticle(update.InlineQuery.ID, "Echo", update.InlineQuery.Query)
        article.Description = update.InlineQuery.Query

        inlineConf := tgbotapi.InlineConfig{
            InlineQueryID: update.InlineQuery.ID,
            IsPersonal:    true,
            CacheTime:     0,
            Results:       []interface{}{article},
        }

        if _, err := bot.AnswerInlineQuery(inlineConf); err != nil {
            log.Println(err)
        }
    }
}
```
shouldn't we have an example for inline queries in `README.md` or is there a breaking change that's about to happen, maybe there should be an interface for results ? so we don't have to use the empty interface. what about an interface that has a method `GetInlineConfig` that returns inlineconfig for that specific result. to have an interface that can group them all together.

**Comment by pyed** [comment]
`update.InlineQuery.From` always equals to `tgbotapi.User{ID:0, FirstName:"", LastName:"", UserName:""}`

**Comment by Syfaro** [comment]
Will throw in an example, sure. The interface is also probably a good idea, I'll play around with that a bit. 

The From always being empty is a bug, need to change it to look for the correct field in the JSON.

**Comment by Syfaro** [comment]
I've been trying to come up with a sane field that they could all share, but there really isn't anything. If someone thinks of something, feel free to reopen this issue, but otherwise I'm closing it.

**Comment by Watn3y** [comment]
Are there any updates on this? I'm having a hard time getting inline queries and inline keyboards to work.

**Comment by jasurbek-suyunov** [comment]
var results []interface{}

for _, event := range events {
    article := tgbotapi.NewInlineQueryResultArticle(event.ID, event.Title, event.Body)
    article.Description = event.Description

   results = append(results, article)
}

inline := tgbotapi.InlineConfig{
    InlineQueryID: inlineQuery.ID,
    IsPersonal: true,
    CacheTime: 0,
    Results: results,
}

_, err := f.API.AnswerInlineQuery(inline)

super code .
