### ISSUE TITLE
Why don't published new releases ?

### ISSUE THREAD

**Issue by sintanial** [go-telegram-bot-api/telegram-bot-api#378]
Why aren't new releases being made? The last release was in 2016, although there are a lot of updates in the master !

**Comment by dilfish** [comment]
You could fork your own version of telegram-bot-api and release it as well.

My git config is:

[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = git@github.com:dilfish/telegram-bot-api-up.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[remote "upstream"]
	url = git@github.com:go-telegram-bot-api/telegram-bot-api.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[pull]
	rebase = true


I would run `git pull upstream master` routinely and push a new date tag.

Also, I have a file list.txt:
~ cat list.txt
v1.0.0
v2.0.0
v2.1.0
v2.2.0
v2.2.1
v3.0.0
v4.0.0
v4.1.0
v4.2.0
v4.2.1
v4.3.0
v4.4.0
v4.5.0
v4.5.1
v4.6
v4.6.1
v4.6.2
v4.6.3
v4.6.4
v5.0.0-rc1


then run:
`for i in `cat list.txt`; do git tag -d $i; done`
to delete local tags

and `for i in `cat list.txt`; do git push --delete origin $i; done` to delete remote tags

After all that, when you get to https://pkg.go.dev/github.com/dilfish/telegram-bot-api-up@v1.0.1
you could see all the latest docs

**Comment by Syfaro** [comment]
New releases are happening now :)
