### ISSUE TITLE
Invalid modules versioning

### ISSUE THREAD

**Issue by vetcher** [go-telegram-bot-api/telegram-bot-api#382]
When I try to install v5, there is an go modules error:
```
go get github.com/go-telegram-bot-api/telegram-bot-api@v5.0.1
go get github.com/go-telegram-bot-api/telegram-bot-api@v5.0.1: github.com/go-telegram-bot-api/telegram-bot-api@v5.0.1: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v5
```

That happens because master branch [should not have](https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning) any tags except v0 or v1. It would works if you create separate branch v5. Check out how [go-pg](https://github.com/go-pg/pg) does it with v8, v9 and v10.

Right now the workaround to get the last version is to manually pin git commit hash: `go get github.com/go-telegram-bot-api/telegram-bot-api@b6df6c2`

**Comment by fiatjaf** [comment]
On a side note, this is the most confusing and broken behavior ever invented for a package manager. Although it breaks my build, it is refreshing to see packages that do not follow it.

**Comment by Syfaro** [comment]
I believe this should be fixed now (or will be shortly, when a release version is tagged).
