### ISSUE TITLE
the webhook request is returned "Webhook is already set"

### ISSUE THREAD

**Issue by LazarenkoA** [go-telegram-bot-api/telegram-bot-api#389]
Hi. 
For some reason, when I install webhook on the url that ngrok gave me (https://github.com/inconshreveable/ngrok), the installation is correct and the bot works, but if you try to install webhook on your url (it is available in the browser), the information is returned that webhook is already set and the bot does not work (does not accept requests)

> 2020/10/27 13:49:44 setWebhook resp: {"ok":true,"result":true,"description":"Webhook is already set"}

What could be the reason?

**Comment by Syfaro** [comment]
Have you tried looking at the output of `getWebhookInfo`? It might have some additional diagnostic information.

https://github.com/go-telegram-bot-api/telegram-bot-api/blob/05e04b526c693e3e104feaa0be23611836af3dcc/bot.go#L499-L501

**Comment by LazarenkoA** [comment]
ok, it worked
