### ISSUE TITLE
No way to remove inline keyboard

### ISSUE THREAD

**Issue by mymmrac** [go-telegram-bot-api/telegram-bot-api#393]
The only way to remove inline keyboard I found was to send an edit message like this:
`editedMsg := tgbotapi.NewEditMessageReplyMarkup(chatId, msgId, tgbotapi.InlineKeyboardMarkup{InlineKeyboard: make([][]tgbotapi.InlineKeyboardButton, 0, 0)})`

Is there any better way to do this?

**Comment by temamagic** [comment]
Telegram api has no method to remove inline keyboard, pass so the best option
```
tgbotapi.InlineKeyboardMarkup{
		InlineKeyboard: make([][]tgbotapi.InlineKeyboardButton, 0),
	}
```
