### ISSUE TITLE
v5.0.1 misses go mod version

### ISSUE THREAD

**Issue by MohammadKarimi23** [go-telegram-bot-api/telegram-bot-api#407]
According to [go mod reference](https://golang.org/ref/mod#major-version-suffixes), "Starting with major version 2, module paths must have a major version suffix like /v2 that matches the major version". 
module version is missing in version `v5.0.1` and causes loss of multiple features developed between `v5.0.0-rc1` and `v5.0.1`

Also, the readme file is missing '/v5' version in module import

**Comment by dc0d** [comment]
In the _go.mod_ file, the first line should be ✅:

```
module github.com/go-telegram-bot-api/telegram-bot-api/v5
```

But it is ❌:

```
module github.com/go-telegram-bot-api/telegram-bot-api
```

**Comment by andig** [comment]
This has been true for every release so far. Wondering if there is any specific reason for not fixing it?

**Comment by MohammadKarimi23** [comment]
I have fixed the issue [in my fork of the repo](https://github.com/MohammadKarimi23/telegram-bot-api), but this needs changes by maintainers of this repo.

**Comment by Syfaro** [comment]
This should be fixed with a new release.
