### ISSUE TITLE
[BUG] NewWebhookWithCert Never Upload CertFile

### ISSUE THREAD

**Issue by zu1k** [go-telegram-bot-api/telegram-bot-api#411]
When Use NewWebhookWithCert , I need to specify URL.

```
func NewWebhookWithCert(link string, file interface{}) WebhookConfig {
	u, _ := url.Parse(link)

	return WebhookConfig{
		URL:         u,
		Certificate: file,
	}
}
```

However, when specify URL, the cert file will never be uploaded

https://github.com/go-telegram-bot-api/telegram-bot-api/blob/bot-api-5.0/configs.go#L948

```
func (config WebhookConfig) useExistingFile() bool {
	return config.URL != nil
}
```

**Comment by Syfaro** [comment]
Wow, that's an incredible oversight. It looks like this should get fixed with #356 without even having realized it at the time.
