### ISSUE TITLE
Menu for bot

### ISSUE THREAD

**Issue by kitt3911** [go-telegram-bot-api/telegram-bot-api#422]
is it possible for a bot to make a menu using your lib?

For example : 

![IMG_20210219_154102](https://user-images.githubusercontent.com/68580920/108486964-e66f1f80-72c8-11eb-8460-b46526b0854a.jpg)

**Comment by kitt3911** [comment]
I just didn't find any documentation on this issue

**Comment by temamagic** [comment]
That's not an issue. Wiki here - https://github.com/go-telegram-bot-api/telegram-bot-api/wiki/Simple-Inline-Keyboard
