### ISSUE TITLE
Use 64-bit integer for userid's

### ISSUE THREAD

**Issue by mr-poluyanov** [go-telegram-bot-api/telegram-bot-api#435]
Telegram warns, that after one of upcoming bot api some user identifiers will be no longer possible to store in a signed 32-bit integer type.

Source: https://core.telegram.org/bots/api#march-9-2021

**Comment by Syfaro** [comment]
Hi, thanks for opening this issue! This problem has already been addressed on the develop branch, #431, and I'm planning to merge it to master and make a new release soon.
