### ISSUE TITLE
'connected_website' field is missing in Message struct

### ISSUE THREAD

**Issue by lempiy** [go-telegram-bot-api/telegram-bot-api#436]
https://core.telegram.org/bots/api#message

Any plans to add this field to struct ?
I wonder why no issues about that yet.

**Comment by Syfaro** [comment]
The library versioning is a bit of a mess right now, but the field is available on the develop branch. Until a new release is tagged, I'd suggest directly using that branch.

https://github.com/go-telegram-bot-api/telegram-bot-api/blob/d0e1dfd8c604cab666e10279936e80acc0953f39/types.go#L512

**Comment by lempiy** [comment]
@Syfaro Thanks for info.
