### ISSUE TITLE
Bot commands

### ISSUE THREAD

**Issue by adobromilskiy** [go-telegram-bot-api/telegram-bot-api#437]
Greetings,

I see in the repository methods SetMyCommands and GetMyCommands. But this methods undefined into the package while I trying go get ... or using go mod tidy. When this methods will be available in the package?

Thanks.

**Comment by Syfaro** [comment]
On v5, you can do something like follows:

```go
commands, err := bot.GetMyCommands()

_, err := bot.Request(tgbotapi.NewSetMyCommands(commands))
```
