### ISSUE TITLE
json: cannot unmarshal bool into Go value of type tgbotapi.Message

### ISSUE THREAD

**Issue by liuaiyuan** [go-telegram-bot-api/telegram-bot-api#438]
v5
```go
msg := tgbotapi.NewDeleteMessage(ctx.Message.Chat.ID, ctx.Message.MessageID)
_,err :=ctx.Send(msg)
fmt.Println(err)
```

**Comment by Syfaro** [comment]
> Send will send a Chattable item to Telegram and provides the
> returned **Message**.

The `deleteMessage` endpoint returns true on success, not a Message.

You're likely looking for the [Request](https://pkg.go.dev/github.com/go-telegram-bot-api/telegram-bot-api/v5#BotAPI.Request) method. 

> Request sends a Chattable to Telegram, and returns the APIResponse.
