### ISSUE TITLE
Getting nil or panics when trying to call Contact struct

### ISSUE THREAD

**Issue by TheGolurk** [go-telegram-bot-api/telegram-bot-api#441]
```go
	for update := range updates {
		if update.Message == nil {
			continue
		}

		fmt.Println("INCOMING FROM:", update.Message.Contact.PhoneNumber)

	}
```

There returns a panic from invalid memory adress, if we Changed to:

```go
fmt.Println("INCOMING FROM:", update.Message.Contact)
```
We get: 
```
<nil>
```

Comments about that?

**Comment by Rusty-Beard** [comment]
> ```go
> 	for update := range updates {
> 		if update.Message == nil {
> 			continue
> 		}
> 
> 		fmt.Println("INCOMING FROM:", update.Message.Contact.PhoneNumber)
> 
> 	}
> ```
> 
> There returns a panic from invalid memory adress, if we Changed to:
> 
> ```go
> fmt.Println("INCOMING FROM:", update.Message.Contact)
> ```
> 
> We get:
> 
> ```
> <nil>
> ```
> 
> Comments about that?

you are trying to access member of nil structure that leads to panic. You should check that `update.Message.Contact` is not `nil` before getting `update.Message.Contact.PhoneNumber`.

**Comment by meguminloli** [comment]
`update.Message.Contact` is a pointer to a Contact structure. If the pointer is nil and you try to access a nil pointer, you will get a panic. Check if the pointer is nil before accessing it.
```
if update.Message.Contact == nil {
    // do something
} else {
    fmt.Println("INCOMING FROM:", update.Message.Contact.PhoneNumber)
}
```

**Comment by armanokka** [comment]
Then close issue
