### ISSUE TITLE
NewBotAPIWithClient apiEndpoint string. how to use?

### ISSUE THREAD

**Issue by ozmy** [go-telegram-bot-api/telegram-bot-api#448]
Good day.
How to use the "apiEndpoint" string in the "NewBotAPIWithClient" function, what is it for?
Please add an example.
Please correct the documentation. There is no such parameter in the documentation.
https://pkg.go.dev/github.com/go-telegram-bot-api/telegram-bot-api#NewBotAPIWithClient
thank you in advance

**Comment by armanokka** [comment]
Это меняет адрес для запросов с api.telegram.org на ваш. Прочтите тут https://core.telegram.org/bots/api#using-a-local-bot-api-server

**Comment by ozmy** [comment]
> It change address for requests from api.telegram.org to your. Read here https://core.telegram.org/bots/api#using-a-local-bot-api-server

Good day.
What is the default value if no change is required?

**Comment by armanokka** [comment]
> > It change address for requests from api.telegram.org to your. Read here https://core.telegram.org/bots/api#using-a-local-bot-api-server
> 
> Good day.
> What is the default value if no change is required?

It is api.telegram.org

**Comment by liyishuai** [comment]
> Good day. What is the default value if no change is required?

Seems to be `https://api.telegram.org/bot%s/%s`:
https://github.com/go-telegram-bot-api/telegram-bot-api/blob/4fe428c77a68a9903ab5bfcaecb978003ce0424b/configs.go#L12-L19
https://github.com/go-telegram-bot-api/telegram-bot-api/blob/4fe428c77a68a9903ab5bfcaecb978003ce0424b/bot.go#L36-L41

**Comment by ozmy** [comment]
> > Good day. What is the default value if no change is required?
> 
> Seems to be `https://api.telegram.org/bot%s/%s`:
> 
> https://github.com/go-telegram-bot-api/telegram-bot-api/blob/4fe428c77a68a9903ab5bfcaecb978003ce0424b/configs.go#L12-L19
> 
> 
> https://github.com/go-telegram-bot-api/telegram-bot-api/blob/4fe428c77a68a9903ab5bfcaecb978003ce0424b/bot.go#L36-L41

good day
Thank you.
In my project I am using the "NewBotAPIWithClient" function to configure the proxy server.
But the function requires the line "apiEndpoint" which I don't understand.
I doubt that it is necessary to indicate this particular link

my project:
https://github.com/ozmy/TeleWallBot/blob/master/telewall.go#L570-L583

**Comment by liyishuai** [comment]
> good day Thank you. In my project I am using the "NewBotAPIWithClient" function to configure the proxy server. But the function requires the line "apiEndpoint" which I don't understand. I doubt that it is necessary to indicate this particular link
> 
> my project: https://github.com/ozmy/TeleWallBot/blob/master/telewall.go#L570-L583

Seems like a difference in function type signature between v4 and v5. Which version are you using?
