### ISSUE TITLE
NewMessage string support

### ISSUE THREAD

**Issue by hryamzik** [go-telegram-bot-api/telegram-bot-api#45]
```NewMessage``` accepts ```chatID``` only in ```int64``` format while the API method ```sendMessage``` supports ```Integer``` or ```String```.

Is there a workaround for this? Looks like only ```UploadFile``` supports map format....

**Comment by Syfaro** [comment]
I'm confused what the issue actually is here? 

I suppose there is a missing helper for creating a message to a channel that uses its username, but you can directly create a Message with a ChannelUsername.

**Comment by Syfaro** [comment]
Am I correct in assuming 7bf755956c8c42f346269565bdb433b08a63df0b closes this issue?

**Comment by hryamzik** [comment]
Wow, that was fast! I'll give it a try in a moment.

**Comment by hryamzik** [comment]
Yes, that's it, thank you!
