### ISSUE TITLE
User.Id should be int64

### ISSUE THREAD

**Issue by Rodrijjke** [go-telegram-bot-api/telegram-bot-api#452]
Hello,

According to [documentation](https://core.telegram.org/bots/api#user), field User.id can have more than 32 significant bits. However, in the [code](https://github.com/go-telegram-bot-api/telegram-bot-api/blob/54104a08f947e08c460c45d195076e48e61f0a26/types.go#L92) it is represented as a regular int.
Can int64 be used there?

**Comment by armanokka** [comment]
Already done
