### ISSUE TITLE
Send audio file larger than 50MB

### ISSUE THREAD

**Issue by toniz4** [go-telegram-bot-api/telegram-bot-api#453]
Hello, thanks for developing this awesome library! I'm trying to make a bot that downloads music, but 50MB is not enough. There is any way I can circumvent this limitation?

**Comment by temamagic** [comment]
You must read the docs first. You can run own bot api server

**Comment by armanokka** [comment]
Local Telegram Bot API is the single way. Close your issue

**Comment by soaska** [comment]
> Local Telegram Bot API is the single way. Close your issue

Cant find go-telegram-bot-api`s docs about it. Can you help, please?

**Comment by armanokka** [comment]
> > Local Telegram Bot API is the single way. Close your issue
> 
> Cant find go-telegram-bot-api`s docs about it. Can you help, please?

It's not related to go-telegram-bot-api. You install local bot API to your server and change API_URL in your code from "api.telegram.org" to "localhost" and send requests to yourself. For more: https://core.telegram.org/bots/api#using-a-local-bot-api-server
