### ISSUE TITLE
i can't update go mod version from v5.0.0-rc1 to 5.0.1

### ISSUE THREAD

**Issue by markgenuine** [go-telegram-bot-api/telegram-bot-api#455]
Please, say. How i can update github.com/go-telegram-bot-api/telegram-bot-api/v5 v5.0.0-rc1 to github.com/go-telegram-bot-api/telegram-bot-api/v5 v5.0.1 in module?
Thank you.

**Comment by GregVes** [comment]
> Please, say. How i can update github.com/go-telegram-bot-api/telegram-bot-api/v5 v5.0.0-rc1 to github.com/go-telegram-bot-api/telegram-bot-api/v5 v5.0.1 in module?
> Thank you.

@markgenuine Did you eventually find out how to?
