### ISSUE TITLE
I'm trying to run it on my Android phone, this has error: "read: connection refused"

### ISSUE THREAD

**Issue by QDxQKOAA** [go-telegram-bot-api/telegram-bot-api#457]
Equipment: Xiaomi
Application: termux

I tried compiling to run on Android phone with ARM64 and got the error in the picture. It seems that UDP cannot be used in Terminal, but I wrote a local UDP connection demo by myself, and the connection is accurate. The same code I compiled to Mac and Windows without this error

![run-153121](https://user-images.githubusercontent.com/40877446/122634976-d3078000-d113-11eb-8f58-b3d49ba309b9.png)
![code-153050](https://user-images.githubusercontent.com/40877446/122635033-0cd88680-d114-11eb-8da2-bde75f37772f.png)

**Comment by tjhorner** [comment]
This seems unrelated to the library itself, and the error is happening lower in the stack. Since this happens in a very unusual environment, it would be very helpful if you provided the steps used to compile to ARM, and a sample repo with the full stack trace you are receiving. Thanks

**Comment by HirbodBehnam** [comment]
I think this was a problem with termux and go. This fixed my issue:
https://stackoverflow.com/a/63915298/4213397
