### ISSUE TITLE
running multiple bots

### ISSUE THREAD

**Issue by sSimuSs** [go-telegram-bot-api/telegram-bot-api#463]
### Discussed in https://github.com/go-telegram-bot-api/telegram-bot-api/discussions/462

<div type='discussions-op-text'>

<sup>Originally posted by **sSimuSs** July  6, 2021</sup>
Hello, is it possible to run multiple bots? Thank you) (with the same domain and port)</div>

**Comment by Syfaro** [comment]
I've replied on your discussion thread.
