### ISSUE TITLE
Support for editing a channel's text message

### ISSUE THREAD

**Issue by pyed** [go-telegram-bot-api/telegram-bot-api#465]
Referring to [editMessageText](https://core.telegram.org/bots/api#editmessagetext) it's possible to pass `@channelname` as a `chat_id` to edit a message text inside a channel, currently `tgbotapi` doesn't seem to support that as it requires a `chat_id` of type `int64`, is there a way to edit channel messages ? Or is that something you're working on for the next version ?

**Comment by Syfaro** [comment]
While there should be a helper method for this, it's already possible by manually constructing the config.

```go
editMessageText := tgbotapi.EditMessageTextConfig{
	BaseEdit: tgbotapi.BaseEdit{
		ChannelUsername: channelUsername,
		MessageID: messageID,
	},
	Text: text,
}
```
