### ISSUE TITLE
Missing optional parameters for sending video

### ISSUE THREAD

**Issue by jw-star** [go-telegram-bot-api/telegram-bot-api#466]
supportsStreaming  height  width  thumb

**Comment by jw-star** [comment]
I have transcoded according to the official format，But over 10M, there is no preview
```
ffmpeg -i bb.mp4 -c:v libx264 -crf 23 bbb.mp4
```

**Comment by jw-star** [comment]
![photo1629004557](https://user-images.githubusercontent.com/48782751/129467944-bb48aa1b-9691-4e2e-8558-98dbdd4a28f5.jpeg)

**Comment by jw-star** [comment]
After you add an attribute 
![Screenshot_20210815_164821](https://user-images.githubusercontent.com/48782751/129472730-f85570eb-f733-41cc-9e52-8c70754879ad.jpg)

**Comment by jw-star** [comment]
supportsStreaming  ，I Want the author to add

**Comment by Syfaro** [comment]
All parameters including thumbnail should now be available!
