### ISSUE TITLE
How I can forward users messages?

### ISSUE THREAD

**Issue by chemax** [go-telegram-bot-api/telegram-bot-api#470]
Hi. Telegram Bot API contain this method https://core.telegram.org/method/messages.forwardMessages but I dont see analogue in telegram-bot-api. How I can forward users messages?

**Comment by Syfaro** [comment]
This feature is currently only on the develop branch.

https://github.com/go-telegram-bot-api/telegram-bot-api/blob/309d612d709586e985187a1eaec9dbf48177fb1b/configs.go#L237-L243

**Comment by Syfaro** [comment]
Feature has been merged to master.
