### ISSUE TITLE
Change user ID type to int64

### ISSUE THREAD

**Issue by misha-plus** [go-telegram-bot-api/telegram-bot-api#473]
Hello, currently `int` type used to represent user ID, but on 32-bit machine this type have 32 bits lentgth. And probably it should be changed to `int64` type. Thank you.

> After one of the upcoming Bot API updates, user identifiers will become bigger than 2^31 - 1 and it will be no longer possible to store them in a signed 32-bit integer type. User identifiers will have up to 52 significant bits, so a 64-bit integer or double-precision float type would still be safe for storing them. Please make sure that your code can correctly handle such user identifiers.

https://core.telegram.org/bots/api#june-25-2021

**Comment by mightymatth** [comment]
```go
package main

import (
	"fmt"
	"encoding/json"
)

type User struct {
	ID int `json:"id"`
}

func main() {
	maxUserID := fmt.Sprintf("%d", uint64(1<<52 - 1))
	
	jsonSrc := []byte(fmt.Sprintf(`{ "id": %s }`, maxUserID))
	fmt.Printf("Raw JSON: %s\n", jsonSrc)
	// Raw JSON: { "id": 4503599627370495 }
	
	var user User
	json.Unmarshal(jsonSrc, &user)
	
	fmt.Printf("Parsed UserID: %d", user.ID)
	// Parsed UserID: 4503599627370495
}
```
https://play.golang.org/p/RdE1-Z8kEZU

It seems like parsing should be safe. Can anyone confirm?

**Comment by Syfaro** [comment]
Fixed, now that develop changes have been merged.
