### ISSUE TITLE
Callback Queries do not work? 

### ISSUE THREAD

**Issue by RaphGL** [go-telegram-bot-api/telegram-bot-api#477]
Hi, I was learning how to use this library while writing my own telegram bot, I've even followed your guide on inline keyboards, but callback queries just don't seem to work at all. When debug is set to true I can see the callback queries being received but I just can't resend them or do anything with them at all. 

![image](https://user-images.githubusercontent.com/28673457/133354050-383e6e0b-bf91-499d-8bf9-3b80cb7e758d.png)

**Comment by Syfaro** [comment]
My best guess, given that your code doesn't panic when a callback query comes in, is that you have something like the following before calling your function:

```go
if update.Message == nil {
	continue
}
```
