### ISSUE TITLE
How to check a user joined the channel a lot of member?

### ISSUE THREAD

**Issue by hoangphuong24984** [go-telegram-bot-api/telegram-bot-api#480]
Hi, I have a bot to check the user join my channel. For now, it's not work for me.
If I created a new channel with some member, it's ok, but for my old channel (>40k members: [https://t.me/InfiniteLaunch](https://t.me/InfiniteLaunch)) it's not work.
And it's only listen chat event, can not listen new_member join event.
please help me!!!

```go
u := tgbotapi.NewUpdate(0)
u.Timeout = 60

updates, err := bot.GetUpdatesChan(u)

if err != nil {
	return
}

for update := range updates {
	if update.Message == nil {
		log.Println("message nil", update)
		continue
	}

	if update.Message.NewChatMembers != nil {
		log.Println("Yeah....., NewChatMembers")
		for _, tele := range update.Message.NewChatMembers {
			if !tele.IsBot {
				go addTelegramUser(airdropDAO, tele.UserName, strconv.Itoa(tele.ID), tele.FirstName)
			}
		}
	} else if update.Message.LeftChatMember != nil {
		log.Println("Fuck....., LeftChatMember")
	}

}
```

**Comment by Syfaro** [comment]
You need to ask for `chat_member` updates and then you can get information in the `ChatMember` field of `Update`. This is currently only available in v5 and on the develop branch.

> Service messages about non-bot users joining the chat will be soon removed from large groups. We recommend using the “chat_member” update as a replacement.

I think you could do something like the following. I'm not sure my logic for detecting new members is accurate, but it should at least give you a start.

```go
u := tgbotapi.NewUpdate(0)
u.Timeout = 60
// You might need other allowed update types
u.AllowedUpdates = []string{"message", "chat_member"}

updates := bot.GetUpdatesChan(u)

for update := range updates {
	if update.ChatMember != nil {
		member := update.ChatMember

		if member.NewChatMember.Status == "left" {
			log.Printf("user %d left chat", member.NewChatMember.User.ID)
			continue
		}

		if member.OldChatMember.Status == "left" && member.NewChatMember.Status != "left" && !member.NewChatMember.User.IsBot {
			user := member.NewChatMember.User
			go addTelegramUser(airdropDAO, user.UserName, strconv.FormatInt(user.ID, 10), user.FirstName)
		}
	}
}
```

**Comment by hoangphuong24984** [comment]
@Syfaro thank you so much, it works for me.

**Comment by LazarenkoA** [comment]
Does this work only for polling, and not for webhook?

**Comment by LazarenkoA** [comment]
@Syfaro @hoangphuong24984  Does this work only for polling, and not for webhook?
