### ISSUE TITLE
telegram-bot-api is tagged with `+incompatible`

### ISSUE THREAD

**Issue by aurium** [go-telegram-bot-api/telegram-bot-api#482]
...for stable version 4.6.

This answer may be useful:
https://stackoverflow.com/questions/57355929/what-does-incompatible-in-go-mod-mean-will-it-cause-harm#57372286

**Comment by arisudesu** [comment]
This hasn't been solved for a year, the author promised to solve the issue long ago, yet no fix has been commited.

**Comment by aurium** [comment]
It is ok on version 5, however 5 is RC.

**Comment by Syfaro** [comment]
v5 has been merged to master and a new release will be tagged.
