### ISSUE TITLE
Where is tgbotapi.NewEditMessageMedia?

### ISSUE THREAD

**Issue by illiafox** [go-telegram-bot-api/telegram-bot-api#489]
I can see only tgbotapi.NewEditMessageMediaConfig, but no method. Does it exist?

**Comment by illiafox** [comment]
I try using struct and bot.Send() and it works! 

` bot.Send(tgbotapi.EditMessageMediaConfig{
				BaseEdit: tgbotapi.BaseEdit{
					MessageID: update.CallbackQuery.Message.MessageID,
					ChatID:    update.CallbackQuery.Message.Chat.ID,
				},
				Media: tgbotapi.NewInputMediaPhoto(tgbotapi.FilePath(file)),`

**Comment by pavelpatrin** [comment]
@illiafox thx for example. Not trivial.

**Comment by illiafox** [comment]
> @illiafox thx for example. Not trivial.

It will be a good idea to reopen issue, because i thought that  `New...` Function was added

![IMG_20220319_213609.jpg](https://user-images.githubusercontent.com/61962654/159135832-2fe431ab-6b45-49f3-9878-5023e83f2058.jpg)

**Comment by pavelpatrin** [comment]
@illiafox i know something a bit better....

**Comment by pavelpatrin** [comment]
https://github.com/go-telegram-bot-api/telegram-bot-api/pull/529
