### ISSUE TITLE
How ban user in group?    

### ISSUE THREAD

**Issue by mazanur** [go-telegram-bot-api/telegram-bot-api#490]
Hi, i found config `UnbanChatMemberConfig` for unban user, but i didnt find config for ban user. 
[bot api](https://core.telegram.org/bots/api#banchatmember)

**Comment by Syfaro** [comment]
`banChatMember` was originally called `kickChatMember` and this library apparently never got an update to reflect [that change](https://core.telegram.org/bots/api#june-25-2021).

I'll push an update shortly to rename it, but you can use [`KickChatMemberConfig`](https://pkg.go.dev/github.com/go-telegram-bot-api/telegram-bot-api/v5#KickChatMemberConfig) for now.

**Comment by mazanur** [comment]
Oh, thank you. I can help you and put pull request with renaming method.

**Comment by Syfaro** [comment]
Closed in https://github.com/go-telegram-bot-api/telegram-bot-api/commit/f2ef2729ab6c83b860cde5326e70b3c143b00ec3.
