### ISSUE TITLE
Error sending answer on callback query

### ISSUE THREAD

**Issue by keiqu** [go-telegram-bot-api/telegram-bot-api#492]
Version `v5.4.0-beta.0`

When I send answer on callback message using the `bot.Send()` function, it returns an error:

```
2021/11/19 02:23:27 Endpoint: answerCallbackQuery, params: map[callback_query_id:1268880497923343434 text:some message]
2021/11/19 02:23:28 Endpoint: answerCallbackQuery, response: {"ok":true,"result":true}
2021/11/19 02:23:28 json: cannot unmarshal bool into Go value of type tgbotapi.Message
```

Obviously, this is because the `Send` function expects the result to be a `tgbotapi.Message`, when in fact it is a `bool`.

**Comment by Syfaro** [comment]
You should use the `Request` method instead.

**Comment by keiqu** [comment]
Thanks. Somehow I missed it. Is it a good idea though to allow to use method `Send` with `CallbackConfig` if it leads to an error?

**Comment by Syfaro** [comment]
It's not ideal to allow it, but I'm unsure how to restrict it in a reasonable way. I'd love to hear suggestions if you have any.
