### ISSUE TITLE
Are all structs serializable?

### ISSUE THREAD

**Issue by dc0d** [go-telegram-bot-api/telegram-bot-api#50]
Since the telegram group is not working I ask it here.

We have updates that we receive and chattables that we send and messages which are the result of sending chattables. But chattables are private interfaces which made me suspect if they have also private state.

Can we serialize Update, Message and Chattables to/from JSON safely?

**Comment by Syfaro** [comment]
The Telegram group is working fine for me, what isn't working for you? 

You should be able to JSON serialize any Update or Message for sure, as they come from Telegram as JSON and there are no modifications. As far as I can see most configs should also be serializable, but I'm not entirely sure.

**Comment by dc0d** [comment]
Thanks for reply! Telegram says the bot user can not be found `User @go_telegram_bot_api` not found`.

The part that I am not sure about are the `Chattable`s that are sent in response to `Update`s. `Updates` and `Message`s get serialized fine; to JSON.

**Comment by Syfaro** [comment]
Are you using an old client? It works correctly on my phone and computer. 

It appears that you can serialize `Chattable` items, but you can't deserialize it unless you know what type it should be. If you do know what type it is, it should be fine. You also couldn't serialize a `FileReader` as `io.Reader` doesn't have a way to be serialized.

**Comment by dc0d** [comment]
I'm using Ubuntu client. Also checked on my Android 5 phone. Maybe I'm doing something wrong.

The bot (struct & update channel) should be a single one & authenticate once (correct me please if I'm wrong) and I was hoping I could use NATS to implement the handlers as a (potentially) distributed system and keep the core bot app tidy.

So I thinks that's not possible (easily at least).

Thanks again for reply;
Seems this thread can get closed.

**Comment by Syfaro** [comment]
Yeah, unfortunately this wasn't written with a project like that in mind. Interesting project idea though!
