### ISSUE TITLE
Problem with UploadFiles

### ISSUE THREAD

**Issue by thank243** [go-telegram-bot-api/telegram-bot-api#504]
This is my code:
````golang
	reqs, err :=u.Bot.UploadFiles("sendDocument", nil,[]tgbotapi.RequestFile{{"test", tgbotapi.FileBytes{
		Name:  "",
		Bytes: marshal,
	}}})
	if err != nil {
		log.Errorln(err.Error())
	}
	log.Infoln(string(reqs.Result))
````
But I got below:
````log
time="2021-12-19T15:44:09+08:00" level=error msg="Bad Request: there is no document in the request"
time="2021-12-19T15:44:09+08:00" level=info
````
When I step in UploadFiles func, I found this code below:
````golang
	req, err := http.NewRequest("POST", method, r)
	if err != nil {
		return nil, err
	}

	req.Header.Set("Content-Type", m.FormDataContentType())

	resp, err := bot.Client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
````
And I set a bp on `req, err := http.NewRequest("POST", method, r)`, I saw nothing in `r`
So what's the problem?

**Comment by Syfaro** [comment]
The name of the uploaded file is significant, for a sendDocument request it must be named document. 

Is there some reason you're directly using the `UploadFiles` method directly? You should be able to make requests like `bot.Send(tgbotapi.NewDocument(chatID, tgbotapi.FileBytes{}))`.

**Comment by thank243** [comment]
thanks you. I haven't saw this method before. It works perfect now.
