### ISSUE TITLE
Support message reactions

### ISSUE THREAD

**Issue by mappu** [go-telegram-bot-api/telegram-bot-api#506]
Hi, this repo is awesome, thanks - 

Message reactions were introduced this week in telegram, it would be ideal if this package supported them.

My use case is to sync them to another chat service, so hopefully they come through as part of the normal event stream,

**Comment by Syfaro** [comment]
Hello! 

I'd love to add this, but unfortunately, Telegram hasn't added any kind of reaction support to the Bot API yet. It's possible support will be coming in the future, but there's no indication to if or when this might happen.

https://core.telegram.org/bots/api#recent-changes

**Comment by omerxx** [comment]
Hi, reactions are now available!
