### ISSUE TITLE
Readme example broken

### ISSUE THREAD

**Issue by liyishuai** [go-telegram-bot-api/telegram-bot-api#507]
The README example needs to be updated per #202, which removed `SetWebhook`:
https://github.com/go-telegram-bot-api/telegram-bot-api/blob/4fe428c77a68a9903ab5bfcaecb978003ce0424b/README.md#L90

_Originally posted by @liyishuai in https://github.com/go-telegram-bot-api/telegram-bot-api/pull/202#discussion_r775089714_

**Comment by Syfaro** [comment]
Thanks for opening this issue! I heard this was an issue but it had slipped my mind. 

Should be fixed by https://github.com/go-telegram-bot-api/telegram-bot-api/commit/60c16b67734cf469e708c8b12722cc4c2bc5486e.
