### ISSUE TITLE
How to respond to a callback

### ISSUE THREAD

**Issue by DwarfWizzard** [go-telegram-bot-api/telegram-bot-api#511]
In previous versions of the bot, there was a method that allowed you to respond to a callback. Now he is gone. What is the current way to do this?

**Comment by DwarfWizzard** [comment]
I`m blind. I found answer to my question at examples.

**Comment by MexHigh** [comment]
Well, I'm blind, too. How did you do it?

**Comment by V4LTRA** [comment]
Hello, I just started to study the world of programming and chose GO as the
first language, I haven’t figured it out myself yet.

Вт, 8 марта 2022 г. в 01:03, Leon Schmidt ***@***.***>:
