### ISSUE TITLE
What is the best way to delete a message?

### ISSUE THREAD

**Issue by Algalish** [go-telegram-bot-api/telegram-bot-api#514]
When I do this I get an error BUT the message is deleted correctly.
Thx!

```
msgToDelete := tgbotapi.DeleteMessageConfig{
		ChatID:    chatID,
		MessageID: msgID,
	}

_, err := TelegramBot.Send(msgToDelete)
```

**Comment by Syfaro** [comment]
Hi, 

The `Send` method should be used for endpoints that return messages, the `Request` method should be used for endpoints that don't return meaningful data, such as `deleteMessage`.

```go
msgToDelete := tgbotapi.DeleteMessageConfig{
	ChatID:    chatID,
	MessageID: msgID,
}

_, err := TelegramBot.Request(msgToDelete)
```
