### ISSUE TITLE
Cannot use '"cert"' (type string) as the type RequestFileData for NewWebhookWithCert

### ISSUE THREAD

**Issue by vyacheslav25** [go-telegram-bot-api/telegram-bot-api#515]
`wh, _ := tgbotapi.NewWebhookWithCert("https://tg.localhost:8443/"+bot.Token, "cert")`

Cannot use '"cert"' (type string) as the type RequestFileData Type does not implement 'RequestFileData' as some methods are missing: NeedsUpload() bool UploadData() (string, io.Reader, error) SendData() string

**Comment by Syfaro** [comment]
Whoops, it looks like the README wasn't updated for some changes.

Here's a working example:

https://github.com/go-telegram-bot-api/telegram-bot-api/blob/ef6e421559d82708b59888ba2022da7602284053/bot_test.go#L554
