### ISSUE TITLE
Stopping bot.

### ISSUE THREAD

**Issue by shadrus** [go-telegram-bot-api/telegram-bot-api#52]
I have a bot manager, that creates some bot instances in goroutings. And it must have a posibility to stop them. but i don't see how to stop bot.GetUpdates() here?

```
func (bot *BotAPI) GetUpdatesChan(config UpdateConfig) (<-chan Update, error) {
	updatesChan := make(chan Update, 100)
	go func() {
		for {
			updates, err := bot.GetUpdates(config)
			if err != nil {
				log.Println(err)
				log.Println("Failed to get updates, retrying in 3 seconds...")
				time.Sleep(time.Second * 3)

				continue
			}

			for _, update := range updates {
				if update.UpdateID >= config.Offset {
					config.Offset = update.UpdateID + 1
					updatesChan <- update
				}
			}
		}
	}()
	return updatesChan, nil
}

```
It continues to get Updates until the whole programm is closed. Is it posible to create method for stopping bot?

**Comment by Syfaro** [comment]
I'd suggest implementing a similar function in your own code, with a stop feature designed however you like. Nothing in the `GetUpdatesChan` method is private, so you may recreate it entirely.
