### ISSUE TITLE
Next Step Handler

### ISSUE THREAD

**Issue by NolPixel** [go-telegram-bot-api/telegram-bot-api#520]
Hi, sorry if I miss. How to make step handler? Like this documentation [Step_Example.py](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/step_example.py)  ... I am struggle to figure out.

**Comment by LogansUA** [comment]
Hey, same question, any update on this one?

**Comment by NolPixel** [comment]
> Hey, same question, any update on this one?

Naah,, you must make your own handler. Make props, then pass whats your next and the handler check your props, execute by their value.

Anyway, I recently change to other repository.

**Comment by LogansUA** [comment]
@NolPixel maybe you could share what repo are started to use?

> You can't comment at this time.
