### ISSUE TITLE
How to get all current users in a group? 

### ISSUE THREAD

**Issue by MexHigh** [go-telegram-bot-api/telegram-bot-api#523]
I know that there is a field for `NewChatMembers` for the `Message`  struct, but how to I get all current members of the group, e.g. when adding the Bot afterwards?

**Comment by temamagic** [comment]
Hi, @MexHigh ! Bot API doesn't have such a method to get all users in a chat, so you can't with this lib.

FYI, tdlib can, but it uses telegram client api, not botapi

**Comment by MexHigh** [comment]
Ok thank you for the hint :)
