### ISSUE TITLE
Markdown has a limit ?

### ISSUE THREAD

**Issue by pyed** [go-telegram-bot-api/telegram-bot-api#53]
This is probably unrelated to `tgbotapi` but I'm not sure what's causing this issue, could be telegram's markdown parser ? 

while running the following:

``` go
package main

import (
	"fmt"
	"log"

	"gopkg.in/telegram-bot-api.v4"
)

func main() {
	bot, err := tgbotapi.NewBotAPI("ThatAwesomeToken")
	if err != nil {
		log.Panic(err)
	}

	log.Printf("Authorized on account %s", bot.Self.UserName)

	u := tgbotapi.NewUpdate(0)
	u.Timeout = 60

	updates, err := bot.GetUpdatesChan(u)

	for update := range updates {
		if update.Message == nil {
			continue
		}

		log.Printf("[%s] %s", update.Message.From.UserName, update.Message.Text)

		var text string
		for i := 1; i < 35; i++ {
			text += fmt.Sprintf("*%d*- *%s*, `%s`\n", i, "Hello", "World!")
		}
		fmt.Println(len(text))
		msg := tgbotapi.NewMessage(update.Message.Chat.ID, text)

		msg.ParseMode = "markdown"
		bot.Send(msg)
	}
}
```

it'll just respond with 34 `<n> Hello, World!` with some markdown. notice that all of them will be correctly formatted until the 34th, after the 34th the markdown will vanish!

![screen shot 2016-07-08 at 2 34 52 am](https://cloud.githubusercontent.com/assets/1909519/16673203/c3f82e52-44b4-11e6-94b8-4de30dceded6.png)

**Comment by Syfaro** [comment]
I'd guess it's related to Telegram as there shouldn't be anything in the library that would affect this. 

If anyone finds a workaround, I'd be happy to accept a PR for it. 

Also, I'd suggest asking things like this in the [Telegram group](https://telegram.me/go_telegram_bot_api) instead of making an issue for them.
