### ISSUE TITLE
 Required parameter thumb_url

### ISSUE THREAD

**Issue by toby3d** [go-telegram-bot-api/telegram-bot-api#54]
`thumb_url` it became a required parameter, in consequence of [InlineQueryResultPhoto](https://core.telegram.org/bots/api#inlinequeryresultphoto) function gives an is guaranteed error.

**Comment by Syfaro** [comment]
You can still specify the thumbnail URL. 

```go
result := tgbotapi.NewInlineQueryResultPhoto("id", "http://your-url.tld/photo.jpg")
result.ThumbURL = "http://your-url.tld/thumb.jpg"
```

**Comment by toby3d** [comment]
@Syfaro This is a very nonobvious method. :confused:

**Comment by Syfaro** [comment]
I'm not really sure what to do here. I could change the function, but that would break backwards compatibility.

**Comment by toby3d** [comment]
@Syfaro I do not think that the introduction of a new function was needed. :confused:
