### ISSUE TITLE
How upload an image?

### ISSUE THREAD

**Issue by noarainstorm** [go-telegram-bot-api/telegram-bot-api#550]
How can I upload an image?
In older versions , it could be done like this:
```
msg := tgbotapi.NewImageUpload(update.Message.Chat.ID, "./io.jpg")
bot.Send(msg)
```

**Comment by Gatvik** [comment]
Tag me pls when a solution is found

**Comment by nicourrrn** [comment]
In new version you need use struct that implements interface RequestFileData. For example FilePath.
