### ISSUE TITLE
Not possible edit message by InlineMessageId

### ISSUE THREAD

**Issue by cybertrn** [go-telegram-bot-api/telegram-bot-api#56]
When we set **_InlineMessageId_** in **_BaseEdit_** struct of **_EditMessageTextConfig_** , values of **_ChatID_** and **_MessageID_** not omitted and sets to 0. This gives **Chat not found** error. We need test  **_InlineMessageId_** existence in **BaseEdit.values** func and Add either _inline_message_id_ or _chat_id_ and _message_id_

**Comment by Syfaro** [comment]
Wasn't this already fixed by #55?

**Comment by cybertrn** [comment]
OK! Sorry, I'm used old version...

**Comment by Syfaro** [comment]
No worries :) 

Updating dependencies can be a real pain.
