### ISSUE TITLE
bot.IsMessageToMe syntax

### ISSUE THREAD

**Issue by greenhell1337** [go-telegram-bot-api/telegram-bot-api#562]
Hey, guys. can someone explain how to use the IsMessageToMe method correctly? I tried everything.

`bot.IsMessageToMe(tgbotapi.Message{})`

or

`bot.IsMessageToMe(*update.Message)`

I will be glad to help. I know it's a stupid question, but I've been sitting with him for days.

**Comment by ccioloss** [comment]
@[greenhell1337](https://github.com/greenhell1337)`bot.IsMessageToMe(*update.Message)` is how you should do it. However, note that this method returns `true` only if the sent message contains `@<your_bot_username>` in the message text

**Comment by greenhell1337** [comment]
> @[greenhell1337](https://github.com/greenhell1337)`bot.IsMessageToMe(*update.Message)` is how you should do it. However, note that this method returns `true` only if the sent message contains `@<your_bot_username>` in the message text
