### ISSUE TITLE
answer inline query

### ISSUE THREAD

**Issue by hamidreza01** [go-telegram-bot-api/telegram-bot-api#577]
hello
I need help answering inline query, no functional, no constructor, nothing! 
Please show me a code sample of answering inline query if possible.

**Comment by temamagic** [comment]
Check out wiki

https://github.com/go-telegram-bot-api/telegram-bot-api/wiki/Simple-Inline-Keyboard

**Comment by AvicennaJr** [comment]
> Check out wiki
> 
> https://github.com/go-telegram-bot-api/telegram-bot-api/wiki/Simple-Inline-Keyboard

`bot.AnswerCallbackQuery undefined (type *tgbotapi.BotAPI has no field or method AnswerCallbackQuery)`

I guess we have to make a new method?

**Comment by AvicennaJr** [comment]
> hello I need help answering inline query, no functional, no constructor, nothing! Please show me a code sample of answering inline query if possible.

[CallbackConfig](https://pkg.go.dev/github.com/go-telegram-bot-api/telegram-bot-api/v5#CallbackConfig) is the response type for CallbackQueries. Here's an example on how to use it:


```
responseMsg := tgbotapi.NewCallbackWithAlert(update.CallbackQuery.ID, "A callback response")
if _, err := bot.Request(responseMsg); err != nil {
				log.Panic(err)
}
```

**Comment by SphericalPotatoInVacuum** [comment]
> Check out wiki
> 
> https://github.com/go-telegram-bot-api/telegram-bot-api/wiki/Simple-Inline-Keyboard

I believe hamidreza01 is talking about the inline mode for the bot and the [inline queries](https://core.telegram.org/bots/api#inlinequery) in particular

**Comment by hamidreza01** [comment]
> > Check out wiki
> > https://github.com/go-telegram-bot-api/telegram-bot-api/wiki/Simple-Inline-Keyboard
> 
> I believe hamidreza01 is talking about the inline mode for the bot and the [inline queries](https://core.telegram.org/bots/api#inlinequery) in particular

Yes exactly, it is different from inline keyboards

**Comment by oneart-dev** [comment]
```golang
updates := bot.ListenForWebhook("/" + bot.Token)
for update := range updates {

    if update.InlineQuery == nil {
        continue
    }

    result := tgbotapi.InlineQueryResultArticle{
        Type:  "article",
        ID:    "*UNIQUE_ID*",
        Title: "Title",
        InputMessageContent: tgbotapi.InputTextMessageContent{
            Text: "text inserted after clicking on the result",
        },
    }

    _, err := bot.Send(tgbotapi.InlineConfig{
        InlineQueryID: update.InlineQuery.ID,
        Results:       []interface{}{result},
        CacheTime:     60,
        IsPersonal:    true,
    })
}
```

**Comment by hamidreza01** [comment]
> ```go
> updates := bot.ListenForWebhook("/" + bot.Token)
> for update := range updates {
> 
>     if update.InlineQuery == nil {
>         continue
>     }
> 
>     result := tgbotapi.InlineQueryResultArticle{
>         Type:  "article",
>         ID:    "*UNIQUE_ID*",
>         Title: "Title",
>         InputMessageContent: tgbotapi.InputTextMessageContent{
>             Text: "text inserted after clicking on the result",
>         },
>     }
> 
>     _, err := bot.Send(tgbotapi.InlineConfig{
>         InlineQueryID: update.InlineQuery.ID,
>         Results:       []interface{}{result},
>         CacheTime:     60,
>         IsPersonal:    true,
>     })
> }
> ```
Yes, that is exactly right, thank you
