### ISSUE TITLE
Panic: runtime error

### ISSUE THREAD

**Issue by fernandoguedes** [go-telegram-bot-api/telegram-bot-api#60]
Hello, I'm tried use the `telegram-bot-api` but without success.

My code is the same example of README.

Steps to reproduce the error:

Go: 1.7.3

`go run main.go`

Log:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x49eff6]

goroutine 37 [running]:
panic(0x6213c0, 0xc42000c130)
	/home/fguedes/go/go/src/runtime/panic.go:500 +0x1a1
net/http.(*Client).deadline(0x0, 0xc42002c020, 0x8900000000000000, 0x8)
	/home/fguedes/go/go/src/net/http/client.go:193 +0x26
net/http.(*Client).doFollowingRedirects(0x0, 0xc4203723c0, 0x683bb0, 0x66bf9d, 0x21, 0xc4203f4200)
	/home/fguedes/go/go/src/net/http/client.go:446 +0x8b
net/http.(*Client).Post(0x0, 0xc42039c270, 0x27, 0x66bf9d, 0x21, 0x75e220, 0xc4203f4200, 0x40, 0xc42039c270, 0x27)
	/home/fguedes/go/go/src/net/http/client.go:579 +0xe2
net/http.(*Client).PostForm(0x0, 0xc42039c270, 0x27, 0xc42039c240, 0x2, 0xc42039c270, 0x27)
	/home/fguedes/go/go/src/net/http/client.go:605 +0xdd
gopkg.in/telegram-bot-api%2ev4.(*BotAPI).MakeRequest(0xc4200e2060, 0x665077, 0xa, 0xc42039c240, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/fguedes/go/gandalf/src/gopkg.in/telegram-bot-api.v4/bot.go:60 +0x1b8
gopkg.in/telegram-bot-api%2ev4.(*BotAPI).GetUpdates(0xc4200e2060, 0x0, 0x0, 0x3c, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/fguedes/go/gandalf/src/gopkg.in/telegram-bot-api.v4/bot.go:386 +0xc8
gopkg.in/telegram-bot-api%2ev4.(*BotAPI).GetUpdatesChan.func1(0xc4200e2060, 0xc4203f41a0, 0xc4200e2180)
	/home/fguedes/go/gandalf/src/gopkg.in/telegram-bot-api.v4/bot.go:456 +0x72
created by gopkg.in/telegram-bot-api%2ev4.(*BotAPI).GetUpdatesChan
	/home/fguedes/go/gandalf/src/gopkg.in/telegram-bot-api.v4/bot.go:472 +0xa9
```

Anyone can help me?

**Comment by Syfaro** [comment]
```go
func (c *Client) deadline() time.Time {
	if c.Timeout > 0 { // Line 193
		return time.Now().Add(c.Timeout)
	}
	return time.Time{}
}
```
I am very confused how apparently that line caused a panic.

It seems to be working for me, so I am not sure what could be causing this issue for you.

**Comment by fernandoguedes** [comment]
@Syfaro, what's the go version that you use?

**Comment by Syfaro** [comment]
`go version go1.7.3 darwin/amd64`

**Comment by fernandoguedes** [comment]
I tested in other computer, but occurs the same error.

`2016/11/28 17:32:52 Authorized on account 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x488f46]

goroutine 14 [running]:
panic(0x6213c0, 0xc42000c180)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
net/http.(*Client).deadline(0x0, 0xc420336008, 0xb300000000000000, 0x8)
	/usr/local/go/src/net/http/client.go:193 +0x26
net/http.(*Client).doFollowingRedirects(0x0, 0xc4200d23c0, 0x683bb0, 0x66bf87, 0x21, 0xc4203ae1c0)
	/usr/local/go/src/net/http/client.go:446 +0x8b
net/http.(*Client).Post(0x0, 0xc42036a270, 0x27, 0x66bf87, 0x21, 0x75e220, 0xc4203ae1c0, 0x40, 0xc42036a270, 0x27)
	/usr/local/go/src/net/http/client.go:579 +0xe2
net/http.(*Client).PostForm(0x0, 0xc42036a270, 0x27, 0xc42036a240, 0x2, 0xc42036a270, 0x27)
	/usr/local/go/src/net/http/client.go:605 +0xdd
gopkg.in/telegram-bot-api%2ev4.(*BotAPI).MakeRequest(0xc420074540, 0x665077, 0xa, 0xc42036a240, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/fguedes/Projetos/src/gopkg.in/telegram-bot-api.v4/bot.go:60 +0x1b8
gopkg.in/telegram-bot-api%2ev4.(*BotAPI).GetUpdates(0xc420074540, 0x0, 0x0, 0x3c, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/fguedes/Projetos/src/gopkg.in/telegram-bot-api.v4/bot.go:386 +0xc8
gopkg.in/telegram-bot-api%2ev4.(*BotAPI).GetUpdatesChan.func1(0xc420074540, 0xc4203ae180, 0xc4200746c0)
	/home/fguedes/Projetos/src/gopkg.in/telegram-bot-api.v4/bot.go:456 +0x72
created by gopkg.in/telegram-bot-api%2ev4.(*BotAPI).GetUpdatesChan
	/home/fguedes/Projetos/src/gopkg.in/telegram-bot-api.v4/bot.go:472 +0xa9
exit status 2`

`go version go1.7.3 linux/amd64`

**Comment by fernandoguedes** [comment]
I discovered the error, my API key was wrong.

The API no returns 2xx code causing the error, because request was without `error` check.

I send PR for this, thanks.

**Comment by ElectricCookie** [comment]
For anybody scratching their heads: this also occurs if the bot is not initialized.
