### ISSUE TITLE
How to use ForceReply

### ISSUE THREAD

**Issue by kateile** [go-telegram-bot-api/telegram-bot-api#627]
Hi devs.
I am having problems using ForceReply. Here is what I have tried but doesn't work
```go
	tgId := query.From.ID

	msg := tg.NewMessage(tgId, "")

	msg.Text = fmt.Sprintf("Please type your Phone number")
	msg.ReplyMarkup = tg.ForceReply{
		ForceReply:            true,
		InputFieldPlaceholder: "Type Phone number",
		Selective:             false,
	}
```

I get the following error
```
2023/01/25 13:08:20 Endpoint: editMessageText, response: {"ok":false,"error_code":400,"description":"Bad Request: field \"inline_keyboard\" of the InlineKeyboardMarkup must be an Array"}

2023/01/25 13:08:20 Bad Request: field "inline_keyboard" of the InlineKeyboardMarkup must be an Array
```
I believe I miss something. Any help will be appreciated

**Comment by victormedranop** [comment]
Los unites 2 puertos con que puedo probar son 

***@***.***:~/GoClient $ telnet s4hdev.hiperole.com.do 3299
Trying 148.103.9.40...
Connected to s4hdev.hiperole.com.do.
Escape character is '^]'.
NI_RTERR(��*ERR*1connection timed out-5NI (network interface)75340/bas/753_REL/src/base/ni/nirout.cpp8195RTPENDLIST::timeoutPend: no route received within 5s (CONNECTED)Wed Feb  8 17:13:29 202336SAProuter 40.4 on 'hodevwd00'*ERR*Connection closed by foreign host.

***@***.***:~/GoClient $ telnet s4hdev.hiperole.com.do 8502
Trying 148.103.9.40...
Connected to s4hdev.hiperole.com.do.
Escape character is '^]'.


Y responden.

Victor
