### ISSUE TITLE
Unable to retrieve full error information from APIResponse

### ISSUE THREAD

**Issue by nvx** [go-telegram-bot-api/telegram-bot-api#66]
When a request fails, the Telegram API responds with some useful information in error_code, description, and parameters as per https://core.telegram.org/bots/api#making-requests

Unfortunately, this line of code prevents reading anything from the returned api response other than the description as passed through the error:

https://github.com/go-telegram-bot-api/telegram-bot-api/blob/c034de512afbaa7ef63c2ac1cf6e55721cafff20/bot.go#L84

The most obvious fix would be to change the returned empty struct APIResponse{} to the retrieved apiResp on that line.

This will this flow on to other functions such as AnswerInlineQuery, AnswerCallbackQuery, etc that simply return bot.MakeRequest() directly.

**Comment by Syfaro** [comment]
I'm really confused why I created a new `APIResponse` there instead of just returning it. Thanks for the issue!

**Comment by zelenin** [comment]
https://github.com/go-telegram-bot-api/telegram-bot-api/commit/3866c68e795c67225c59663bd0e84291512965f6
it breaks api errors handling.
