### ISSUE TITLE
The development group doesn't work.

### ISSUE THREAD

**Issue by mshafiee** [go-telegram-bot-api/telegram-bot-api#69]
The development group doesn't work.

**Comment by Jeiwan** [comment]
It works fine for me.

**Comment by Syfaro** [comment]
86 people are currently in it, newest member joined 4 days ago. 

You should be able to just visit this page to join: https://t.me/go_telegram_bot_api

**Comment by dc0d** [comment]
It says "User @go_telegram_bot_api not found". I'm on Ubuntu 16.04 and use Telegram regularly, with other groups and channels without a problem.
