### ISSUE TITLE
Reaction events

### ISSUE THREAD

**Issue by fgazat** [go-telegram-bot-api/telegram-bot-api#709]
Is here any support of message reactions updates?

**Comment by omerxx** [comment]
Hey, I've forked it and added support, already working but I'll work on it further this week to only allow for supported reaction emojis: https://github.com/omerxx/telegram-bot-api

```golang
	config := tgbotapi.SetMessageReactionConfig{
		ChatID:    chatId,
		MessageID: messageId,
		Reactions: []tgbotapi.ReactionType{{
			Type:  "emoji",
			Emoji: "❤",
		}},
	}
	if err := update.Bot.SetMessageReaction(config); err != nil {
		return err
	}
```
