### ISSUE TITLE
how to send message with image 

### ISSUE THREAD

**Issue by hyahm** [go-telegram-bot-api/telegram-bot-api#757]
how to send message with image 
like this
![image](https://github.com/user-attachments/assets/f5ebbb66-5e99-4057-8203-5c8a8b33e017)

**Comment by CodeExplorerX** [comment]
secondMessageText := "test msg"

photoPath := "./img.jpg"
photoMsg := tgbotapi.NewPhoto(chatID, tgbotapi.FilePath(photoPath))
photoMsg.Caption = secondMessageText

if _, err := bot.Send(photoMsg); err != nil {
    log.Printf("Error sending photo: %v", err)
}

**Comment by hyahm** [comment]
Thanks
