### ISSUE TITLE
updatesChannel type visibility scope

### ISSUE THREAD

**Issue by EvdokimovN** [go-telegram-bot-api/telegram-bot-api#76]
Hello, there! Just wanted to inquirer is there any reason type `updatesChannel` is private? 

As far as I can see it has single public method `Clear()` which is not used anywhere in the library which in my eyes creates a contradiction where type has public method but no consumer can use it due to type being private.

The issue came up when I switched to webHook from polling. I would love to add switch from polling to webHook with single boolean parameter and use code similar to this

```
var updates  tgbotapi.updatesChannel
if isWebHook{
  //listen for updates
} else {
 //get updates channel
}

for update := range updates{
// deal with update
}
```
but since `updatesChannel` is private I cannot do this as updates would be uninitialised.

**Comment by Syfaro** [comment]
There was no reason that type should have been private. 

You should be able to do that now.
