### ISSUE TITLE
BUTTON_TYPE_INVALID

### ISSUE THREAD

**Issue by toby3d** [go-telegram-bot-api/telegram-bot-api#78]
`Bad Request: BUTTON_TYPE_INVALID` if I try remove InlineKeyboard in message by this code:
```go
edit := tgbotapi.NewEditMessageReplyMarkup(
    callback.Message.Chat.ID,
    callback.Message.MessageID,
    tgbotapi.InlineKeyboardMarkup{},
)
bot.Send(edit)
```

P.S.: Also, as and with this variant:
```go
var markup tgbotapi.InlineKeyboardMarkup
edit := tgbotapi.NewEditMessageText(
    callback.Message.Chat.ID,
    callback.Message.MessageID,
    "sample text",
)
edit.ReplyMarkup = &markup
bot.Send(edit)
```

**Comment by toby3d** [comment]
Same error with any message which contains `InlineKeyboardButtonSwitch`. :neutral_face:

**Comment by TheBeastOfCaerbannog** [comment]
This issue was already fixed in #65 , but this change is not included in latest stable build (gopkg.in/telegram-bot-api.v4). You should import build from master branch to get this fix.

**Comment by toby3d** [comment]
@TheBeastOfCaerbannog I completely removed the local clone and download the latest master commit - errors are stored.

**Comment by TheBeastOfCaerbannog** [comment]
@toby3d 
Oh, sorry, I tried out only your second example.
If you are trying to remove inline keyboard you could do something like this:
```
edit := tgbotapi.NewEditMessageReplyMarkup(
  update.CallbackQuery.Message.Chat.ID,
  update.CallbackQuery.Message.MessageID,
  tgbotapi.InlineKeyboardMarkup{
    InlineKeyboard: make([][]tgbotapi.InlineKeyboardButton,0),
  },
)
bot.Send(edit)
```
There is also PR (#77) for helper method to remove inline keyboard

**Comment by toby3d** [comment]
@TheBeastOfCaerbannog Okay, thanks. It remains to deal with the switch buttons.

**Comment by TheBeastOfCaerbannog** [comment]
@toby3d No problem :)
But as I said, second example was fine for me.
Could you please post a bit more details?

**Comment by toby3d** [comment]
@TheBeastOfCaerbannog Any message with SwitchButton(s) just do not sent with an BUTTON_TYPE_INVALID error in the log.

**Comment by TheBeastOfCaerbannog** [comment]
So something like [this example](https://gist.github.com/TheBeastOfCaerbannog/1c1cf728cf533a345ece0897ea8854f8) fails on your PC?

**Comment by toby3d** [comment]
@TheBeastOfCaerbannog example it works fine.

**Comment by toby3d** [comment]
@TheBeastOfCaerbannog Hah, it worked only when I changed the path from `"gopkg.in/telegram-bot-api.v4"` to `"github.com/go-telegram-bot-api/telegram-bot-api"`. Despite the fact that in `~/go/src/gopkg.in/telegram-bot-api.v4` I downloaded and manually lay the last state in the master.
