### ISSUE TITLE
Implement change logger

### ISSUE THREAD

**Issue by ViGo5190** [go-telegram-bot-api/telegram-bot-api#81]
I want to use logrus, or my logger. Can you implement `setLogger`?

**Comment by Syfaro** [comment]
Are you logging debug statements? The only use of the log package is in the updates loop, which is trivial to rewrite in your own application with a custom logger.

**Comment by radaiming** [comment]
But another concern is, when GetUpdates fails, it may return an error containing the API url, and the token is also in the url, which should not be printed
