### ISSUE TITLE
[Request] Getting user's @

### ISSUE THREAD

**Issue by xBigG** [go-telegram-bot-api/telegram-bot-api#83]
Is there a way to get user's @ with go?
I'm getting lot of troubles with this.

**Comment by ReanSn0w** [comment]
update.Message.From.UserName in standart example, will give you @username without "@" for every update in chan

**Comment by Syfaro** [comment]
Username should be in `update.Message.From.UserName` as @ReanSn0w said. If that is empty, the user does not have a username. If you need the '@' in front of it, you will just have to prepend it.
