### ISSUE TITLE
CallbackQuery always returns an empty Message

### ISSUE THREAD

**Issue by toby3d** [go-telegram-bot-api/telegram-bot-api#86]
This is strange, but the sent callback through pressing the keyboard button from the inline search result does not return the body of the parent. Only identifiers, data and date.

**Comment by Syfaro** [comment]
This might be intentional? https://core.telegram.org/bots/api#callbackquery

**Comment by toby3d** [comment]
I'm not sure. All fresh inline results do not return the body of the parent in any form. Those. The structure is filled everywhere except Message.

**Comment by zhuharev** [comment]
Have you dealt with your problem? @toby3d
