### ISSUE TITLE
NewInlineKeyboardMarkup 

### ISSUE THREAD

**Issue by dzhabrailovsn** [go-telegram-bot-api/telegram-bot-api#87]
Please show example with NewInlineKeyboardMarkup  with callbacks for processing . I dont understand how i should procces the event when user click inline button.

**Comment by toby3d** [comment]
For example:
https://github.com/HentaiDB/HentaiDBot/blob/master/inline.go#L160
https://github.com/HentaiDB/HentaiDBot/blob/master/callback.go#L359
