### ISSUE TITLE
Question : making keyboard button with loop

### ISSUE THREAD

**Issue by jinsyu** [go-telegram-bot-api/telegram-bot-api#88]
First of all, It is not an issue though but I really hard to work on making keyboard button.
But sadly, I could not make it.  it is beyond my  ability, so i am posting this article for any help or tips.
i want to make keyboard buttons from data that from looping.
One data get one button row.
like 
----
data1
----
data2
----
data3

Any help or tips would be great for me. thanks.

**Comment by toby3d** [comment]
Example by array of locale names (`[]string{"russian", "english", "chinese"...}`): https://github.com/HentaiDB/HentaiDBot/blob/master/callback.go#L304

**Comment by jinsyu** [comment]
Thanks it works!
