### ISSUE TITLE
No Caption in NewVideoUpload

### ISSUE THREAD

**Issue by daciwei** [go-telegram-bot-api/telegram-bot-api#89]
The code:
```

	// don't have caption
	video := tgbotapi.NewVideoUpload(int64(11111), "video.mp4")
	video.Caption = "TEST"
	bot.Send(video)

	//has caption
	document := tgbotapi.NewDocumentUpload(int64(11111), "video.mp4")
	document.Caption = "TEST"
	bot.Send(document)


```
And result:

<img width="309" alt="screen shot 2017-05-14 at 09 44 40" src="https://cloud.githubusercontent.com/assets/13871989/26031824/1311103e-388a-11e7-90da-1f9b71d25f1f.png">

**Comment by yanzay** [comment]
@Syfaro could you check pull-request, please?
