### ISSUE TITLE
Add other minor changes

### ISSUE THREAD

**Issue by toby3d** [go-telegram-bot-api/telegram-bot-api#91]
![image](https://cloud.githubusercontent.com/assets/5412322/26221858/60623dcc-3c31-11e7-98bc-3f8db8515f18.png)

**Comment by Arman92** [comment]
Support for VideoNote has been added.
#93

**Comment by korjavin** [comment]
Waiting for payments also

**Comment by MrYadro** [comment]
Payments API is now done #96

**Comment by MrYadro** [comment]
Minor changes #97

**Comment by toby3d** [comment]
Done! Thanks!
