### ISSUE TITLE
Support context

### ISSUE THREAD

**Issue by nvx** [go-telegram-bot-api/telegram-bot-api#92]
The net/http library supports contexts since go 1.7 for both client and server. This can allow graceful cancelling of requests.

Use-cases I can think of involve gracefully stopping a GetUpdates() call waiting for timeout and when posting messages during shutdown of a bot.

**Comment by yanzay** [comment]
But it will break compatibility with go 1.6 and earlier, for someone it may be critical.

**Comment by nvx** [comment]
As per the Go Release Cycle, only the current and -1 version are supported. As we are on go 1.8, this means only go 1.8 and go 1.7 are supported, while go 1.6 and earlier are not supported.

That said, this sort of change would possibly require a gopkg version bump anyway, so people on go 1.6 using an older version should be fine as is on the old gopkg version anyway.

**Comment by yanzay** [comment]
AFAIK Google App Engine still use go 1.6 and it seems to be a popular platform for hosting bots. I don't use it, but trying to save compatibility from 1.6 to tip. Could someone confirm or deny that go 1.6 still in use?

**Comment by nvx** [comment]
Hmm I was unaware of AppEngine still using Go 1.6. Checking the AppEngine docs it looks like The "Flexible environment" uses Go 1.8, but the "Standard environment" is still on Go 1.6.

That said, the standard environment appears to be locked down in a few ways, so I'm not actually sure if this library would run in it as-is.  The flexible environment you can do anything and this would work fine though obviously.

It would be good to hear from someone using this library in AppEngine to find out if it does work in the standard environment or not.

**Comment by Syfaro** [comment]
Yeah, hearing from anyone using this in a limited environment would definitely be beneficial. I don't want to break backwards compatibility if possible but I also don't want to limit new features if it doesn't really help anyone.

**Comment by koorgoo** [comment]
@nvx if you need basic functionality only (sending messages, receiving updates), please, take a look at my package https://github.com/koorgoo/telegram. I started it with context in mind, so it could be useful to you.
