### ISSUE TITLE
Can I serialize a payload from a different source into a Chattable?

### ISSUE THREAD

**Issue by m90** [go-telegram-bot-api/telegram-bot-api#99]
I use this library to connect a telegram bot to an api.ai NLP backend. api.ai offers a "Custom payload" functionality where in certain cases I will receive a valid payload that could be sent to the telegram bot API already.

Instead I currently deserialize this payload into an intermediate format and then use the methods provided by the library to rebuild the same message.

This works but is pretty tedious and needs constant updating when something new is being added.

Is there a non-hacky way of passing through a payload directly or would I need to resort to my very own `http.Client` here?

**Comment by zhuharev** [comment]
Can you provide example of "payload"?

**Comment by m90** [comment]
It'd be just a data structure that could be passed through directly to the Telegram Bot API like:

```json
{
	"text": "Hello?",
	"reply_markup": {
		"keyboard": ["Hello!"],
	},
	"one_time_keyboard": true,
	"resize_keyboard": true
}
```

**Comment by Syfaro** [comment]
You can use `MakeRequest` if you have a `url.Values`, but that's the lowest level this library ever deals with. It passes the `url.Values` directly into go's `Client.PostForm` method. 

Given that this example seems extremely simple, it might be easiest to send a request yourself with your custom data without using the library at all. The Bot API is very simple to deal with.
